wire_shark_number_type_set = {'Boolean', 
'Floating point (double-precision)', 
'Frame number', 
'Signed integer (1 byte)',
'Signed integer (2 bytes)',
'Signed integer (4 bytes)',
'Signed integer (8 bytes)',
'Time offset',
'Unsigned integer (1 byte)',
'Unsigned integer (2 bytes)',
'Unsigned integer (3 bytes)',
'Unsigned integer (4 bytes)',
'Unsigned integer (8 bytes)',
'Unsigned integer, 2 bytes',
'Unsigned integer, 4 bytes'}

wire_shark_ipaddr_type_set = {
'IPv4 address',
'IPv6 address'
}



wire_shark_type_lookup_map = {'comment': 'Character string',
 'frame.bblog': 'Character string',
 'frame.bblog.serial_nr': 'Unsigned integer (4 bytes)',
 'frame.bblog.ticks': 'Unsigned integer (4 bytes)',
 'frame.cap_len': 'Unsigned integer (4 bytes)',
 'frame.cb_copy': 'Boolean',
 'frame.cb_pen': 'Unsigned integer (4 bytes)',
 'frame.coloring_rule.name': 'Character string',
 'frame.coloring_rule.string': 'Character string',
 'frame.comment': 'Character string',
 'frame.comment.expert': 'Label',
 'frame.dlt': 'Signed integer (2 bytes)',
 'frame.drop_count': 'Unsigned integer (8 bytes)',
 'frame.encap_type': 'Signed integer (2 bytes)',
 'frame.file_off': 'Signed integer (8 bytes)',
 'frame.ignored': 'Boolean',
 'frame.incomplete': 'Label',
 'frame.interface_description': 'Character string',
 'frame.interface_id': 'Unsigned integer (4 bytes)',
 'frame.interface_name': 'Character string',
 'frame.interface_queue': 'Unsigned integer (4 bytes)',
 'frame.len': 'Unsigned integer (4 bytes)',
 'frame.len_lt_caplen': 'Label',
 'frame.link_nr': 'Unsigned integer (2 bytes)',
 'frame.marked': 'Boolean',
 'frame.md5_hash': 'Character string',
 'frame.number': 'Unsigned integer (4 bytes)',
 'frame.offset_shift': 'Time offset',
 'frame.p2p_dir': 'Signed integer (1 byte)',
 'frame.p_prot_data': 'Unsigned integer (4 bytes)',
 'frame.packet_flags': 'Unsigned integer (4 bytes)',
 'frame.packet_flags_crc_error': 'Boolean',
 'frame.packet_flags_direction': 'Unsigned integer (4 bytes)',
 'frame.packet_flags_fcs_length': 'Unsigned integer (4 bytes)',
 'frame.packet_flags_packet_too_error': 'Boolean',
 'frame.packet_flags_packet_too_short_error': 'Boolean',
 'frame.packet_flags_preamble_error': 'Boolean',
 'frame.packet_flags_reception_type': 'Unsigned integer (4 bytes)',
 'frame.packet_flags_reserved': 'Unsigned integer (4 bytes)',
 'frame.packet_flags_start_frame_delimiter_error': 'Boolean',
 'frame.packet_flags_symbol_error': 'Boolean',
 'frame.packet_flags_unaligned_frame_error': 'Boolean',
 'frame.packet_flags_wrong_inter_frame_gap_error': 'Boolean',
 'frame.packet_id': 'Unsigned integer (8 bytes)',
 'frame.pcaplog.data': 'Byte sequence',
 'frame.pcaplog.data_length': 'Unsigned integer (4 bytes)',
 'frame.pcaplog.data_type': 'Unsigned integer (4 bytes)',
 'frame.pkt_len': 'Unsigned integer (4 bytes)',
 'frame.protocols': 'Character string',
 'frame.ref_time': 'Label',
 'frame.section_number': 'Unsigned integer (4 bytes)',
 'frame.time': 'Date and time',
 'frame.time_delta': 'Time offset',
 'frame.time_delta_displayed': 'Time offset',
 'frame.time_epoch': 'Time offset',
 'frame.time_invalid': 'Label',
 'frame.time_relative': 'Time offset',
 'frame.verdict': 'Character string',
 'frame.verdict.ebpf_tc': 'Signed integer (8 bytes)',
 'frame.verdict.ebpf_xdp': 'Signed integer (8 bytes)',
 'frame.verdict.hw': 'Byte sequence',
 'frame.verdict.unknown': 'Byte sequence',
 'eth.addr': 'Ethernet or other MAC address',
 'eth.addr.oui': 'Unsigned integer (3 bytes)',
 'eth.addr.oui_resolved': 'Character string',
 'eth.addr_resolved': 'Character string',
 'eth.dst': 'Ethernet or other MAC address',
 'eth.dst.ig': 'Boolean',
 'eth.dst.lg': 'Boolean',
 'eth.dst.oui': 'Unsigned integer (3 bytes)',
 'eth.dst.oui_resolved': 'Character string',
 'eth.dst_resolved': 'Character string',
 'eth.fcs': 'Unsigned integer (4 bytes)',
 'eth.fcs.status': 'Unsigned integer (1 byte)',
 'eth.fcs_bad': 'Label',
 'eth.fcs_bad.expert': 'Label',
 'eth.fcs_good': 'Boolean',
 'eth.ig': 'Boolean',
 'eth.invalid_lentype': 'Unsigned integer (2 bytes)',
 'eth.invalid_lentype.expert': 'Label',
 'eth.len': 'Unsigned integer (2 bytes)',
 'eth.len.past_end': 'Label',
 'eth.lg': 'Boolean',
 'eth.padding': 'Byte sequence',
 'eth.padding_bad': 'Label',
 'eth.src': 'Ethernet or other MAC address',
 'eth.src.ig': 'Boolean',
 'eth.src.lg': 'Boolean',
 'eth.src.oui': 'Unsigned integer (3 bytes)',
 'eth.src.oui_resolved': 'Character string',
 'eth.src_not_group': 'Label',
 'eth.src_resolved': 'Character string',
 'eth.trailer': 'Byte sequence',
 'eth.type': 'Unsigned integer (2 bytes)',
 'eth.vlan.cfi': 'Unsigned integer (2 bytes)',
 'eth.vlan.id': 'Unsigned integer (2 bytes)',
 'eth.vlan.pri': 'Unsigned integer (2 bytes)',
 'eth.vlan.tpid': 'Unsigned integer (2 bytes)',
 'ip.addr': 'IPv4 address',
 'ip.bogus_header_length': 'Label',
 'ip.bogus_ip_length': 'Label',
 'ip.bogus_ip_version': 'Label',
 'ip.checksum': 'Unsigned integer (2 bytes)',
 'ip.checksum.status': 'Unsigned integer (1 byte)',
 'ip.checksum_bad': 'Boolean',
 'ip.checksum_bad.expert': 'Label',
 'ip.checksum_calculated': 'Unsigned integer (2 bytes)',
 'ip.checksum_good': 'Boolean',
 'ip.cipso.categories': 'Character string',
 'ip.cipso.doi': 'Unsigned integer (4 bytes)',
 'ip.cipso.malformed': 'Label',
 'ip.cipso.sensitivity_level': 'Unsigned integer (1 byte)',
 'ip.cipso.tag_data': 'Byte sequence',
 'ip.cipso.tag_type': 'Unsigned integer (1 byte)',
 'ip.cur_rt': 'IPv4 address',
 'ip.cur_rt_host': 'Character string',
 'ip.dsfield': 'Unsigned integer (1 byte)',
 'ip.dsfield.ce': 'Unsigned integer (1 byte)',
 'ip.dsfield.dscp': 'Unsigned integer (1 byte)',
 'ip.dsfield.ecn': 'Unsigned integer (1 byte)',
 'ip.dsfield.ect': 'Unsigned integer (1 byte)',
 'ip.dst': 'IPv4 address',
 'ip.dst_host': 'Character string',
 'ip.empty_rt': 'IPv4 address',
 'ip.empty_rt_host': 'Character string',
 'ip.evil_packet': 'Label',
 'ip.flags': 'Unsigned integer (1 byte)',
 'ip.flags.df': 'Boolean',
 'ip.flags.mf': 'Boolean',
 'ip.flags.rb': 'Boolean',
 'ip.flags.sf': 'Boolean',
 'ip.frag_offset': 'Unsigned integer (2 bytes)',
 'ip.fragment': 'Frame number',
 'ip.fragment.count': 'Unsigned integer (4 bytes)',
 'ip.fragment.error': 'Frame number',
 'ip.fragment.multipletails': 'Boolean',
 'ip.fragment.overlap': 'Boolean',
 'ip.fragment.overlap.conflict': 'Boolean',
 'ip.fragment.toolongfragment': 'Boolean',
 'ip.fragments': 'Byte sequence',
 'ip.geoip.asnum': 'Unsigned integer (4 bytes)',
 'ip.geoip.city': 'Character string',
 'ip.geoip.country': 'Character string',
 'ip.geoip.country_iso': 'Character string',
 'ip.geoip.dst_asnum': 'Unsigned integer (4 bytes)',
 'ip.geoip.dst_city': 'Character string',
 'ip.geoip.dst_country': 'Character string',
 'ip.geoip.dst_country_iso': 'Character string',
 'ip.geoip.dst_isp': 'Character string',
 'ip.geoip.dst_lat': 'Floating point (double-precision)',
 'ip.geoip.dst_lon': 'Floating point (double-precision)',
 'ip.geoip.dst_org': 'Character string',
 'ip.geoip.dst_summary': 'Character string',
 'ip.geoip.isp': 'Character string',
 'ip.geoip.lat': 'Floating point (double-precision)',
 'ip.geoip.lon': 'Floating point (double-precision)',
 'ip.geoip.org': 'Character string',
 'ip.geoip.src_asnum': 'Unsigned integer (4 bytes)',
 'ip.geoip.src_city': 'Character string',
 'ip.geoip.src_country': 'Character string',
 'ip.geoip.src_country_iso': 'Character string',
 'ip.geoip.src_isp': 'Character string',
 'ip.geoip.src_lat': 'Floating point (double-precision)',
 'ip.geoip.src_lon': 'Floating point (double-precision)',
 'ip.geoip.src_org': 'Character string',
 'ip.geoip.src_summary': 'Character string',
 'ip.hdr_len': 'Unsigned integer (1 byte)',
 'ip.host': 'Character string',
 'ip.id': 'Unsigned integer (2 bytes)',
 'ip.len': 'Unsigned integer (2 bytes)',
 'ip.nop': 'Label',
 'ip.opt.addr': 'IPv4 address',
 'ip.opt.ext_sec_add_sec_info': 'Byte sequence',
 'ip.opt.ext_sec_add_sec_info_format_code': 'Unsigned integer (1 byte)',
 'ip.opt.flag': 'Unsigned integer (1 byte)',
 'ip.opt.id_number': 'Unsigned integer (2 bytes)',
 'ip.opt.len': 'Unsigned integer (1 byte)',
 'ip.opt.len.invalid': 'Label',
 'ip.opt.mtu': 'Unsigned integer (2 bytes)',
 'ip.opt.ohc': 'Unsigned integer (2 bytes)',
 'ip.opt.originator': 'IPv4 address',
 'ip.opt.overflow': 'Unsigned integer (1 byte)',
 'ip.opt.padding': 'Byte sequence',
 'ip.opt.ptr': 'Unsigned integer (1 byte)',
 'ip.opt.ptr.before_address': 'Label',
 'ip.opt.ptr.middle_address': 'Label',
 'ip.opt.qs_func': 'Unsigned integer (1 byte)',
 'ip.opt.qs_nonce': 'Unsigned integer (4 bytes)',
 'ip.opt.qs_rate': 'Unsigned integer (1 byte)',
 'ip.opt.qs_reserved': 'Unsigned integer (4 bytes)',
 'ip.opt.qs_ttl': 'Unsigned integer (1 byte)',
 'ip.opt.qs_ttl_diff': 'Unsigned integer (1 byte)',
 'ip.opt.qs_unused': 'Unsigned integer (1 byte)',
 'ip.opt.ra': 'Unsigned integer (2 bytes)',
 'ip.opt.rhc': 'Unsigned integer (2 bytes)',
 'ip.opt.sec_cl': 'Unsigned integer (1 byte)',
 'ip.opt.sec_prot_auth_doe': 'Boolean',
 'ip.opt.sec_prot_auth_flags': 'Unsigned integer (1 byte)',
 'ip.opt.sec_prot_auth_fti': 'Boolean',
 'ip.opt.sec_prot_auth_genser': 'Boolean',
 'ip.opt.sec_prot_auth_nsa': 'Boolean',
 'ip.opt.sec_prot_auth_sci': 'Boolean',
 'ip.opt.sec_prot_auth_siop_esi': 'Boolean',
 'ip.opt.sec_prot_auth_unassigned': 'Unsigned integer (1 byte)',
 'ip.opt.sec_rfc791_comp': 'Unsigned integer (2 bytes)',
 'ip.opt.sec_rfc791_hr': 'Character string',
 'ip.opt.sec_rfc791_sec': 'Unsigned integer (2 bytes)',
 'ip.opt.sec_rfc791_tcc': 'Character string',
 'ip.opt.sid': 'Unsigned integer (2 bytes)',
 'ip.opt.time_stamp': 'Unsigned integer (4 bytes)',
 'ip.opt.time_stamp_addr': 'IPv4 address',
 'ip.opt.type': 'Unsigned integer (1 byte)',
 'ip.opt.type.class': 'Unsigned integer (1 byte)',
 'ip.opt.type.copy': 'Boolean',
 'ip.opt.type.number': 'Unsigned integer (1 byte)',
 'ip.proto': 'Unsigned integer (1 byte)',
 'ip.reassembled.data': 'Byte sequence',
 'ip.reassembled.length': 'Unsigned integer (4 bytes)',
 'ip.reassembled_in': 'Frame number',
 'ip.rec_rt': 'IPv4 address',
 'ip.rec_rt_host': 'Character string',
 'ip.src': 'IPv4 address',
 'ip.src_host': 'Character string',
 'ip.src_rt': 'IPv4 address',
 'ip.src_rt_host': 'Character string',
 'ip.subopt_too_long': 'Label',
 'ip.tos': 'Unsigned integer (1 byte)',
 'ip.tos.cost': 'Boolean',
 'ip.tos.delay': 'Boolean',
 'ip.tos.precedence': 'Unsigned integer (1 byte)',
 'ip.tos.reliability': 'Boolean',
 'ip.tos.throughput': 'Boolean',
 'ip.ttl': 'Unsigned integer (1 byte)',
 'ip.ttl.lncb': 'Label',
 'ip.ttl.too_small': 'Label',
 'ip.version': 'Unsigned integer (1 byte)',
 'mptcp.analysis.echoed_key_mismatch': 'Label',
 'mptcp.analysis.missing_algorithm': 'Label',
 'mptcp.analysis.unexpected_idsn': 'Label',
 'mptcp.analysis.unsupported_algorithm': 'Label',
 'mptcp.connection.echoed_key_mismatch': 'Label',
 'mptcp.connection.missing_algorithm': 'Label',
 'mptcp.connection.unsupported_algorithm': 'Label',
 'mptcp.dss.infinite_mapping': 'Label',
 'mptcp.dss.missing_mapping': 'Label',
 'tcp.ack': 'Unsigned integer (4 bytes)',
 'tcp.ack.nonzero': 'Label',
 'tcp.ack_raw': 'Unsigned integer (4 bytes)',
 'tcp.analysis': 'Label',
 'tcp.analysis.ack_lost_segment': 'Label',
 'tcp.analysis.ack_rtt': 'Time offset',
 'tcp.analysis.acks_frame': 'Frame number',
 'tcp.analysis.bytes_in_flight': 'Unsigned integer (4 bytes)',
 'tcp.analysis.duplicate_ack': 'Label',
 'tcp.analysis.duplicate_ack_frame': 'Frame number',
 'tcp.analysis.duplicate_ack_num': 'Unsigned integer (4 bytes)',
 'tcp.analysis.fast_retransmission': 'Label',
 'tcp.analysis.flags': 'Label',
 'tcp.analysis.initial_rtt': 'Time offset',
 'tcp.analysis.keep_alive': 'Label',
 'tcp.analysis.keep_alive_ack': 'Label',
 'tcp.analysis.lost_segment': 'Label',
 'tcp.analysis.out_of_order': 'Label',
 'tcp.analysis.push_bytes_sent': 'Unsigned integer (4 bytes)',
 'tcp.analysis.retransmission': 'Label',
 'tcp.analysis.reused_ports': 'Label',
 'tcp.analysis.rto': 'Time offset',
 'tcp.analysis.rto_frame': 'Frame number',
 'tcp.analysis.spurious_retransmission': 'Label',
 'tcp.analysis.tfo_ack': 'Label',
 'tcp.analysis.tfo_ignored': 'Label',
 'tcp.analysis.tfo_syn': 'Label',
 'tcp.analysis.window_full': 'Label',
 'tcp.analysis.window_update': 'Label',
 'tcp.analysis.zero_window': 'Label',
 'tcp.analysis.zero_window_probe': 'Label',
 'tcp.analysis.zero_window_probe_ack': 'Label',
 'tcp.bogus_header_length': 'Label',
 'tcp.checksum': 'Unsigned integer (2 bytes)',
 'tcp.checksum.ffff': 'Label',
 'tcp.checksum.status': 'Unsigned integer (1 byte)',
 'tcp.checksum_bad': 'Boolean',
 'tcp.checksum_bad.expert': 'Label',
 'tcp.checksum_calculated': 'Unsigned integer (2 bytes)',
 'tcp.checksum_good': 'Boolean',
 'tcp.completeness': 'Unsigned integer (1 byte)',
 'tcp.connection.fin': 'Label',
 'tcp.connection.fin_active': 'Label',
 'tcp.connection.fin_passive': 'Label',
 'tcp.connection.rst': 'Label',
 'tcp.connection.sack': 'Label',
 'tcp.connection.syn': 'Label',
 'tcp.connection.synack': 'Label',
 'tcp.continuation_to': 'Frame number',
 'tcp.data': 'Byte sequence',
 'tcp.dstport': 'Unsigned integer (2 bytes)',
 'tcp.fin_retransmission': 'Frame number',
 'tcp.flags': 'Unsigned integer (2 bytes)',
 'tcp.flags.ace': 'Unsigned integer (1 byte)',
 'tcp.flags.ack': 'Boolean',
 'tcp.flags.ae': 'Boolean',
 'tcp.flags.cwr': 'Boolean',
 'tcp.flags.ece': 'Boolean',
 'tcp.flags.ecn': 'Boolean',
 'tcp.flags.fin': 'Boolean',
 'tcp.flags.ns': 'Boolean',
 'tcp.flags.push': 'Boolean',
 'tcp.flags.res': 'Boolean',
 'tcp.flags.reset': 'Boolean',
 'tcp.flags.str': 'Character string',
 'tcp.flags.syn': 'Boolean',
 'tcp.flags.urg': 'Boolean',
 'tcp.hdr_len': 'Unsigned integer (1 byte)',
 'tcp.len': 'Unsigned integer (4 bytes)',
 'tcp.non_zero_bytes_after_eol': 'Label',
 'tcp.nop': 'Label',
 'tcp.nxtseq': 'Unsigned integer (4 bytes)',
 'tcp.option.len.invalid': 'Label',
 'tcp.option_kind': 'Unsigned integer (1 byte)',
 'tcp.option_len': 'Unsigned integer (1 byte)',
 'tcp.options': 'Byte sequence',
 'tcp.options.acc_ecn.eceb': 'Unsigned integer (3 bytes)',
 'tcp.options.acc_ecn.ee0b': 'Unsigned integer (3 bytes)',
 'tcp.options.acc_ecn.ee1b': 'Unsigned integer (3 bytes)',
 'tcp.options.ao.keyid': 'Unsigned integer (1 byte)',
 'tcp.options.ao.mac': 'Byte sequence',
 'tcp.options.ao.rnextkeyid': 'Unsigned integer (1 byte)',
 'tcp.options.cc': 'Boolean',
 'tcp.options.cc_value': 'Unsigned integer (4 bytes)',
 'tcp.options.ccecho': 'Boolean',
 'tcp.options.ccnew': 'Boolean',
 'tcp.options.echo': 'Boolean',
 'tcp.options.echo_reply': 'Boolean',
 'tcp.options.echo_value': 'Unsigned integer (4 bytes)',
 'tcp.options.experimental': 'Byte sequence',
 'tcp.options.experimental.data': 'Byte sequence',
 'tcp.options.experimental.exid': 'Unsigned integer (2 bytes)',
 'tcp.options.experimental.magic_number': 'Unsigned integer (2 bytes)',
 'tcp.options.md5': 'Boolean',
 'tcp.options.md5.digest': 'Byte sequence',
 'tcp.options.mood': 'Boolean',
 'tcp.options.mood_val': 'Character string',
 'tcp.options.mptcp.addaddrtrunchmac': 'Unsigned integer (8 bytes)',
 'tcp.options.mptcp.addrid': 'Unsigned integer (1 byte)',
 'tcp.options.mptcp.backup.flag': 'Unsigned integer (1 byte)',
 'tcp.options.mptcp.checksum': 'Unsigned integer (2 bytes)',
 'tcp.options.mptcp.checksumreq.flags': 'Unsigned integer (1 byte)',
 'tcp.options.mptcp.dataack': 'Unsigned integer (8 bytes)',
 'tcp.options.mptcp.dataack8.flag': 'Unsigned integer (1 byte)',
 'tcp.options.mptcp.dataackpresent.flag': 'Unsigned integer (1 byte)',
 'tcp.options.mptcp.datafin.flag': 'Unsigned integer (1 byte)',
 'tcp.options.mptcp.datalvllen': 'Unsigned integer (2 bytes)',
 'tcp.options.mptcp.dataseqno': 'Unsigned integer (8 bytes)',
 'tcp.options.mptcp.dseqn8.flag': 'Unsigned integer (1 byte)',
 'tcp.options.mptcp.dseqnpresent.flag': 'Unsigned integer (1 byte)',
 'tcp.options.mptcp.echo': 'Unsigned integer (1 byte)',
 'tcp.options.mptcp.extensibility.flag': 'Unsigned integer (1 byte)',
 'tcp.options.mptcp.flag_T.flag': 'Boolean',
 'tcp.options.mptcp.flag_U.flag': 'Boolean',
 'tcp.options.mptcp.flag_V.flag': 'Boolean',
 'tcp.options.mptcp.flag_W.flag': 'Boolean',
 'tcp.options.mptcp.flags': 'Unsigned integer (1 byte)',
 'tcp.options.mptcp.ipv4': 'IPv4 address',
 'tcp.options.mptcp.ipv6': 'IPv6 address',
 'tcp.options.mptcp.ipver': 'Unsigned integer (1 byte)',
 'tcp.options.mptcp.nomoresubflows.flag': 'Unsigned integer (1 byte)',
 'tcp.options.mptcp.port': 'Unsigned integer (2 bytes)',
 'tcp.options.mptcp.rawdataack': 'Unsigned integer (8 bytes)',
 'tcp.options.mptcp.rawdataseqno': 'Unsigned integer (8 bytes)',
 'tcp.options.mptcp.recvkey': 'Unsigned integer (8 bytes)',
 'tcp.options.mptcp.recvtok': 'Unsigned integer (4 bytes)',
 'tcp.options.mptcp.reserved': 'Unsigned integer (2 bytes)',
 'tcp.options.mptcp.reserved.flag': 'Unsigned integer (1 byte)',
 'tcp.options.mptcp.rst_reason': 'Unsigned integer (1 byte)',
 'tcp.options.mptcp.sendhmac': 'Byte sequence',
 'tcp.options.mptcp.sendkey': 'Unsigned integer (8 bytes)',
 'tcp.options.mptcp.sendmac': 'Unsigned integer (4 bytes)',
 'tcp.options.mptcp.sendrand': 'Unsigned integer (4 bytes)',
 'tcp.options.mptcp.sendtrunchmac': 'Unsigned integer (8 bytes)',
 'tcp.options.mptcp.sendtruncmac': 'Unsigned integer (8 bytes)',
 'tcp.options.mptcp.sha1.flag': 'Unsigned integer (1 byte)',
 'tcp.options.mptcp.sha256.flag': 'Unsigned integer (1 byte)',
 'tcp.options.mptcp.subflowseqno': 'Unsigned integer (4 bytes)',
 'tcp.options.mptcp.subtype': 'Unsigned integer (1 byte)',
 'tcp.options.mptcp.version': 'Unsigned integer (1 byte)',
 'tcp.options.mss': 'Label',
 'tcp.options.mss.absent': 'Label',
 'tcp.options.mss.present': 'Label',
 'tcp.options.mss_val': 'Unsigned integer (2 bytes)',
 'tcp.options.qs': 'Boolean',
 'tcp.options.qs.rate': 'Unsigned integer (1 byte)',
 'tcp.options.qs.ttl_diff': 'Unsigned integer (1 byte)',
 'tcp.options.rvbd.probe': 'Boolean',
 'tcp.options.rvbd.probe.appli_ver': 'Unsigned integer (2 bytes)',
 'tcp.options.rvbd.probe.client.ip': 'IPv4 address',
 'tcp.options.rvbd.probe.flags': 'Unsigned integer (1 byte)',
 'tcp.options.rvbd.probe.flags.last': 'Boolean',
 'tcp.options.rvbd.probe.flags.notcfe': 'Boolean',
 'tcp.options.rvbd.probe.flags.probe': 'Boolean',
 'tcp.options.rvbd.probe.flags.server': 'Boolean',
 'tcp.options.rvbd.probe.flags.ssl': 'Boolean',
 'tcp.options.rvbd.probe.len': 'Unsigned integer (1 byte)',
 'tcp.options.rvbd.probe.prober': 'IPv4 address',
 'tcp.options.rvbd.probe.proxy.ip': 'IPv4 address',
 'tcp.options.rvbd.probe.proxy.port': 'Unsigned integer (2 bytes)',
 'tcp.options.rvbd.probe.reserved': 'Unsigned integer (1 byte)',
 'tcp.options.rvbd.probe.storeid': 'Unsigned integer (4 bytes)',
 'tcp.options.rvbd.probe.type1': 'Unsigned integer (1 byte)',
 'tcp.options.rvbd.probe.type2': 'Unsigned integer (1 byte)',
 'tcp.options.rvbd.probe.version': 'Unsigned integer (1 byte)',
 'tcp.options.rvbd.probe.version_raw': 'Unsigned integer (1 byte)',
 'tcp.options.rvbd.trpy': 'Boolean',
 'tcp.options.rvbd.trpy.client.port': 'Unsigned integer (2 bytes)',
 'tcp.options.rvbd.trpy.dst.ip': 'IPv4 address',
 'tcp.options.rvbd.trpy.dst.port': 'Unsigned integer (2 bytes)',
 'tcp.options.rvbd.trpy.flags': 'Unsigned integer (2 bytes)',
 'tcp.options.rvbd.trpy.flags.chksum': 'Boolean',
 'tcp.options.rvbd.trpy.flags.fw_rst': 'Boolean',
 'tcp.options.rvbd.trpy.flags.fw_rst_inner': 'Boolean',
 'tcp.options.rvbd.trpy.flags.fw_rst_probe': 'Boolean',
 'tcp.options.rvbd.trpy.flags.mode': 'Boolean',
 'tcp.options.rvbd.trpy.flags.oob': 'Boolean',
 'tcp.options.rvbd.trpy.src.ip': 'IPv4 address',
 'tcp.options.rvbd.trpy.src.port': 'Unsigned integer (2 bytes)',
 'tcp.options.sack': 'Boolean',
 'tcp.options.sack.count': 'Unsigned integer (1 byte)',
 'tcp.options.sack.dsack': 'Label',
 'tcp.options.sack.dsack_le': 'Unsigned integer (4 bytes)',
 'tcp.options.sack.dsack_re': 'Unsigned integer (4 bytes)',
 'tcp.options.sack_le': 'Unsigned integer (4 bytes)',
 'tcp.options.sack_perm': 'Boolean',
 'tcp.options.sack_re': 'Unsigned integer (4 bytes)',
 'tcp.options.scps': 'Boolean',
 'tcp.options.scps.binding': 'Unsigned integer (1 byte)',
 'tcp.options.scps.binding.data': 'Byte sequence',
 'tcp.options.scps.binding.id': 'Unsigned integer (1 byte)',
 'tcp.options.scps.binding.len': 'Unsigned integer (1 byte)',
 'tcp.options.scps.vector': 'Unsigned integer (1 byte)',
 'tcp.options.scpsflags.bets': 'Boolean',
 'tcp.options.scpsflags.compress': 'Boolean',
 'tcp.options.scpsflags.nlts': 'Boolean',
 'tcp.options.scpsflags.reserved': 'Unsigned integer (1 byte)',
 'tcp.options.scpsflags.reserved1': 'Boolean',
 'tcp.options.scpsflags.reserved2': 'Boolean',
 'tcp.options.scpsflags.reserved3': 'Boolean',
 'tcp.options.scpsflags.snack1': 'Boolean',
 'tcp.options.scpsflags.snack2': 'Boolean',
 'tcp.options.snack': 'Boolean',
 'tcp.options.snack.le': 'Unsigned integer (2 bytes)',
 'tcp.options.snack.offset': 'Unsigned integer (2 bytes)',
 'tcp.options.snack.re': 'Unsigned integer (2 bytes)',
 'tcp.options.snack.sequence': 'Label',
 'tcp.options.snack.size': 'Unsigned integer (2 bytes)',
 'tcp.options.tar.reserved': 'Unsigned integer (1 byte)',
 'tcp.options.tarr.rate': 'Unsigned integer (1 byte)',
 'tcp.options.tfo': 'Label',
 'tcp.options.tfo.cookie': 'Byte sequence',
 'tcp.options.tfo.request': 'Label',
 'tcp.options.time_stamp': 'Boolean',
 'tcp.options.timestamp.tsecr': 'Unsigned integer (4 bytes)',
 'tcp.options.timestamp.tsval': 'Unsigned integer (4 bytes)',
 'tcp.options.timestamp.tsval.syncookie.ecn': 'Boolean',
 'tcp.options.timestamp.tsval.syncookie.sack': 'Boolean',
 'tcp.options.timestamp.tsval.syncookie.timestamp': 'Unsigned integer (4 bytes)',
 'tcp.options.timestamp.tsval.syncookie.wscale': 'Unsigned integer (1 byte)',
 'tcp.options.type': 'Unsigned integer (1 byte)',
 'tcp.options.type.class': 'Unsigned integer (1 byte)',
 'tcp.options.type.copy': 'Boolean',
 'tcp.options.type.number': 'Unsigned integer (1 byte)',
 'tcp.options.unknown.payload': 'Byte sequence',
 'tcp.options.user_to': 'Boolean',
 'tcp.options.user_to_granularity': 'Boolean',
 'tcp.options.user_to_val': 'Unsigned integer (2 bytes)',
 'tcp.options.wscale': 'Boolean',
 'tcp.options.wscale.multiplier': 'Unsigned integer (2 bytes)',
 'tcp.options.wscale.shift': 'Unsigned integer (1 byte)',
 'tcp.options.wscale.shift.invalid': 'Label',
 'tcp.options.wscale_val': 'Unsigned integer (1 byte)',
 'tcp.payload': 'Byte sequence',
 'tcp.pdu.last_frame': 'Frame number',
 'tcp.pdu.size': 'Unsigned integer (4 bytes)',
 'tcp.pdu.time': 'Time offset',
 'tcp.port': 'Unsigned integer (2 bytes)',
 'tcp.proc.dstcmd': 'Character string',
 'tcp.proc.dstpid': 'Unsigned integer (4 bytes)',
 'tcp.proc.dstuid': 'Unsigned integer (4 bytes)',
 'tcp.proc.dstuname': 'Character string',
 'tcp.proc.srccmd': 'Character string',
 'tcp.proc.srcpid': 'Unsigned integer (4 bytes)',
 'tcp.proc.srcuid': 'Unsigned integer (4 bytes)',
 'tcp.proc.srcuname': 'Character string',
 'tcp.reassembled.data': 'Byte sequence',
 'tcp.reassembled.length': 'Unsigned integer (4 bytes)',
 'tcp.reassembled_in': 'Frame number',
 'tcp.reset_cause': 'Character string',
 'tcp.segment': 'Frame number',
 'tcp.segment.count': 'Unsigned integer (4 bytes)',
 'tcp.segment.error': 'Frame number',
 'tcp.segment.multipletails': 'Boolean',
 'tcp.segment.overlap': 'Boolean',
 'tcp.segment.overlap.conflict': 'Boolean',
 'tcp.segment.toolongfragment': 'Boolean',
 'tcp.segment_data': 'Byte sequence',
 'tcp.segments': 'Label',
 'tcp.seq': 'Unsigned integer (4 bytes)',
 'tcp.seq_raw': 'Unsigned integer (4 bytes)',
 'tcp.short_segment': 'Label',
 'tcp.srcport': 'Unsigned integer (2 bytes)',
 'tcp.stream': 'Unsigned integer (4 bytes)',
 'tcp.suboption_malformed': 'Label',
 'tcp.syncookie.hash': 'Unsigned integer (3 bytes)',
 'tcp.syncookie.mss': 'Unsigned integer (1 byte)',
 'tcp.syncookie.time': 'Unsigned integer (1 byte)',
 'tcp.time_delta': 'Time offset',
 'tcp.time_relative': 'Time offset',
 'tcp.urgent_pointer': 'Unsigned integer (2 bytes)',
 'tcp.urgent_pointer.non_zero': 'Label',
 'tcp.window_size': 'Unsigned integer (4 bytes)',
 'tcp.window_size_scalefactor': 'Signed integer (4 bytes)',
 'tcp.window_size_value': 'Unsigned integer (2 bytes)',
 'tls.alert_message': 'Label',
 'tls.alert_message.desc': 'Unsigned integer (1 byte)',
 'tls.alert_message.level': 'Unsigned integer (1 byte)',
 'tls.app_data': 'Byte sequence',
 'tls.app_data_proto': 'Character string',
 'tls.change_cipher_spec': 'Label',
 'tls.compress_certificate.algorithm': 'Unsigned integer (2 bytes)',
 'tls.compress_certificate.algorithms_length': 'Unsigned integer (1 byte)',
 'tls.compress_certificate.compressed_certificate_message': 'Byte sequence',
 'tls.compress_certificate.compressed_certificate_message.length': 'Unsigned integer (3 bytes)',
 'tls.compress_certificate.uncompressed_length': 'Unsigned integer (3 bytes)',
 'tls.connection_id': 'Byte sequence',
 'tls.connection_id_length': 'Unsigned integer (1 byte)',
 'tls.decompression_error': 'Label',
 'tls.early_data.max_early_data_size': 'Unsigned integer (4 bytes)',
 'tls.esni.encrypted_sni': 'Byte sequence',
 'tls.esni.encrypted_sni_length': 'Unsigned integer (2 bytes)',
 'tls.esni.nonce': 'Byte sequence',
 'tls.esni.record_digest': 'Byte sequence',
 'tls.esni.record_digest_length': 'Unsigned integer (2 bytes)',
 'tls.esni.suite': 'Unsigned integer (2 bytes)',
 'tls.extension.oid_filters.oid': 'ASN.1 object identifier',
 'tls.extension.oid_filters.oid_length': 'Unsigned integer (1 byte)',
 'tls.extension.oid_filters.values_length': 'Unsigned integer (2 bytes)',
 'tls.extension.oid_filters_length': 'Unsigned integer (2 bytes)',
 'tls.extension.psk_ke_mode': 'Unsigned integer (1 byte)',
 'tls.extension.psk_ke_modes_length': 'Unsigned integer (1 byte)',
 'tls.handshake': 'Label',
 'tls.handshake.cert_type': 'Unsigned integer (1 byte)',
 'tls.handshake.cert_type.type': 'Unsigned integer (1 byte)',
 'tls.handshake.cert_type.types': 'Label',
 'tls.handshake.cert_type.types_len': 'Unsigned integer (1 byte)',
 'tls.handshake.cert_types': 'Label',
 'tls.handshake.cert_types_count': 'Unsigned integer (1 byte)',
 'tls.handshake.cert_url.padding': 'Label',
 'tls.handshake.cert_url.sha1': 'Byte sequence',
 'tls.handshake.cert_url.url': 'Character string',
 'tls.handshake.cert_url.url_hash': 'Label',
 'tls.handshake.cert_url.url_hash_len': 'Unsigned integer (2 bytes)',
 'tls.handshake.cert_url.url_len': 'Unsigned integer (2 bytes)',
 'tls.handshake.cert_url_type': 'Unsigned integer (1 byte)',
 'tls.handshake.certificate': 'Byte sequence',
 'tls.handshake.certificate_length': 'Unsigned integer (3 bytes)',
 'tls.handshake.certificate_request_context': 'Byte sequence',
 'tls.handshake.certificate_request_context_length': 'Unsigned integer (1 byte)',
 'tls.handshake.certificates': 'Label',
 'tls.handshake.certificates_length': 'Unsigned integer (3 bytes)',
 'tls.handshake.challenge': 'Label',
 'tls.handshake.challenge_length': 'Unsigned integer (2 bytes)',
 'tls.handshake.cipher_spec_len': 'Unsigned integer (2 bytes)',
 'tls.handshake.cipher_suites_length': 'Unsigned integer (2 bytes)',
 'tls.handshake.cipherspec': 'Unsigned integer (3 bytes)',
 'tls.handshake.ciphersuite': 'Unsigned integer (2 bytes)',
 'tls.handshake.ciphersuites': 'Label',
 'tls.handshake.clear_key_data': 'Label',
 'tls.handshake.clear_key_length': 'Unsigned integer (2 bytes)',
 'tls.handshake.client_cert_vrfy.sig': 'Byte sequence',
 'tls.handshake.client_cert_vrfy.sig_len': 'Unsigned integer (2 bytes)',
 'tls.handshake.client_point': 'Byte sequence',
 'tls.handshake.client_point_len': 'Unsigned integer (1 byte)',
 'tls.handshake.comp_method': 'Unsigned integer (1 byte)',
 'tls.handshake.comp_methods': 'Label',
 'tls.handshake.comp_methods_length': 'Unsigned integer (1 byte)',
 'tls.handshake.connection_id': 'Label',
 'tls.handshake.connection_id_length': 'Unsigned integer (2 bytes)',
 'tls.handshake.cred.pubkey': 'Byte sequence',
 'tls.handshake.cred.pubkey_len': 'Unsigned integer (3 bytes)',
 'tls.handshake.cred.signature': 'Byte sequence',
 'tls.handshake.cred.signature_len': 'Unsigned integer (2 bytes)',
 'tls.handshake.cred.valid_time': 'Unsigned integer (2 bytes)',
 'tls.handshake.dname': 'Label',
 'tls.handshake.dname_len': 'Unsigned integer (2 bytes)',
 'tls.handshake.dnames': 'Label',
 'tls.handshake.dnames_len': 'Unsigned integer (2 bytes)',
 'tls.handshake.dnames_truncated': 'Label',
 'tls.handshake.encrypted_key': 'Label',
 'tls.handshake.encrypted_key_length': 'Unsigned integer (2 bytes)',
 'tls.handshake.epms': 'Byte sequence',
 'tls.handshake.epms_len': 'Unsigned integer (2 bytes)',
 'tls.handshake.exponent': 'Byte sequence',
 'tls.handshake.exponent_len': 'Unsigned integer (2 bytes)',
 'tls.handshake.extension.data': 'Byte sequence',
 'tls.handshake.extension.heartbeat.mode': 'Unsigned integer (1 byte)',
 'tls.handshake.extension.len': 'Unsigned integer (2 bytes)',
 'tls.handshake.extension.type': 'Unsigned integer (2 bytes)',
 'tls.handshake.extensions.cookie': 'Byte sequence',
 'tls.handshake.extensions.cookie_len': 'Unsigned integer (2 bytes)',
 'tls.handshake.extensions.psk.binders': 'Label',
 'tls.handshake.extensions.psk.binders_len': 'Unsigned integer (2 bytes)',
 'tls.handshake.extensions.psk.identities.length': 'Unsigned integer (2 bytes)',
 'tls.handshake.extensions.psk.identity.identity': 'Byte sequence',
 'tls.handshake.extensions.psk.identity.identity_length': 'Unsigned integer (2 bytes)',
 'tls.handshake.extensions.psk.identity.obfuscated_ticket_age': 'Unsigned integer (4 bytes)',
 'tls.handshake.extensions.psk.identity.selected': 'Unsigned integer (2 bytes)',
 'tls.handshake.extensions.supported_version': 'Unsigned integer (2 bytes)',
 'tls.handshake.extensions.supported_versions_len': 'Unsigned integer (1 byte)',
 'tls.handshake.extensions_alpn_len': 'Unsigned integer (2 bytes)',
 'tls.handshake.extensions_alpn_list': 'Label',
 'tls.handshake.extensions_alpn_str': 'Character string',
 'tls.handshake.extensions_alpn_str_len': 'Unsigned integer (1 byte)',
 'tls.handshake.extensions_alps.settings': 'Byte sequence',
 'tls.handshake.extensions_alps_alpn_list': 'Label',
 'tls.handshake.extensions_alps_alpn_str': 'Character string',
 'tls.handshake.extensions_alps_alpn_str_len': 'Unsigned integer (1 byte)',
 'tls.handshake.extensions_alps_len': 'Unsigned integer (2 bytes)',
 'tls.handshake.extensions_ec_point_format': 'Unsigned integer (1 byte)',
 'tls.handshake.extensions_ec_point_formats': 'Label',
 'tls.handshake.extensions_ec_point_formats_length': 'Unsigned integer (1 byte)',
 'tls.handshake.extensions_key_share_client_length': 'Unsigned integer (2 bytes)',
 'tls.handshake.extensions_key_share_group': 'Unsigned integer (2 bytes)',
 'tls.handshake.extensions_key_share_key_exchange': 'Byte sequence',
 'tls.handshake.extensions_key_share_key_exchange_length': 'Unsigned integer (2 bytes)',
 'tls.handshake.extensions_key_share_selected_group': 'Unsigned integer (2 bytes)',
 'tls.handshake.extensions_length': 'Unsigned integer (2 bytes)',
 'tls.handshake.extensions_npn': 'Character string',
 'tls.handshake.extensions_npn_str_len': 'Unsigned integer (1 byte)',
 'tls.handshake.extensions_padding_data': 'Byte sequence',
 'tls.handshake.extensions_reneg_info': 'Byte sequence',
 'tls.handshake.extensions_reneg_info_len': 'Unsigned integer (1 byte)',
 'tls.handshake.extensions_server_name': 'Character string',
 'tls.handshake.extensions_server_name_len': 'Unsigned integer (2 bytes)',
 'tls.handshake.extensions_server_name_list_len': 'Unsigned integer (2 bytes)',
 'tls.handshake.extensions_server_name_type': 'Unsigned integer (1 byte)',
 'tls.handshake.extensions_srp_len': 'Unsigned integer (1 byte)',
 'tls.handshake.extensions_srp_username': 'Character string',
 'tls.handshake.extensions_status_request_exts_len': 'Unsigned integer (2 bytes)',
 'tls.handshake.extensions_status_request_len': 'Unsigned integer (2 bytes)',
 'tls.handshake.extensions_status_request_list_len': 'Unsigned integer (2 bytes)',
 'tls.handshake.extensions_status_request_responder_ids_len': 'Unsigned integer (2 bytes)',
 'tls.handshake.extensions_status_request_type': 'Unsigned integer (1 byte)',
 'tls.handshake.extensions_supported_group': 'Unsigned integer (2 bytes)',
 'tls.handshake.extensions_supported_groups': 'Label',
 'tls.handshake.extensions_supported_groups_length': 'Unsigned integer (2 bytes)',
 'tls.handshake.fragment': 'Frame number',
 'tls.handshake.fragment.count': 'Unsigned integer (4 bytes)',
 'tls.handshake.fragments': 'Label',
 'tls.handshake.g': 'Byte sequence',
 'tls.handshake.g_len': 'Unsigned integer (2 bytes)',
 'tls.handshake.hint': 'Byte sequence',
 'tls.handshake.hint_len': 'Unsigned integer (2 bytes)',
 'tls.handshake.identity': 'Byte sequence',
 'tls.handshake.identity_len': 'Unsigned integer (2 bytes)',
 'tls.handshake.ja3': 'Character string',
 'tls.handshake.ja3_full': 'Character string',
 'tls.handshake.ja3s': 'Character string',
 'tls.handshake.ja3s_full': 'Character string',
 'tls.handshake.key_arg': 'Label',
 'tls.handshake.key_arg_length': 'Unsigned integer (2 bytes)',
 'tls.handshake.key_update.request_update': 'Unsigned integer (1 byte)',
 'tls.handshake.length': 'Unsigned integer (3 bytes)',
 'tls.handshake.max_fragment_length': 'Unsigned integer (1 byte)',
 'tls.handshake.md5_hash': 'Label',
 'tls.handshake.modulus': 'Byte sequence',
 'tls.handshake.modulus_len': 'Unsigned integer (2 bytes)',
 'tls.handshake.npn_padding': 'Byte sequence',
 'tls.handshake.npn_padding_len': 'Unsigned integer (1 byte)',
 'tls.handshake.npn_selected_protocol': 'Character string',
 'tls.handshake.npn_selected_protocol_len': 'Unsigned integer (1 byte)',
 'tls.handshake.ocsp_response_len': 'Unsigned integer (3 bytes)',
 'tls.handshake.ocsp_response_list_len': 'Unsigned integer (3 bytes)',
 'tls.handshake.p': 'Byte sequence',
 'tls.handshake.p_len': 'Unsigned integer (2 bytes)',
 'tls.handshake.random': 'Byte sequence',
 'tls.handshake.random_bytes': 'Byte sequence',
 'tls.handshake.random_time': 'Date and time',
 'tls.handshake.rc': 'Byte sequence',
 'tls.handshake.rc_len': 'Unsigned integer (1 byte)',
 'tls.handshake.reassembled_in': 'Frame number',
 'tls.handshake.rs': 'Byte sequence',
 'tls.handshake.rs_len': 'Unsigned integer (1 byte)',
 'tls.handshake.server_curve_type': 'Unsigned integer (1 byte)',
 'tls.handshake.server_named_curve': 'Unsigned integer (2 bytes)',
 'tls.handshake.server_point': 'Byte sequence',
 'tls.handshake.server_point_len': 'Unsigned integer (1 byte)',
 'tls.handshake.session_id': 'Byte sequence',
 'tls.handshake.session_id_hit': 'Boolean',
 'tls.handshake.session_id_length': 'Unsigned integer (2 bytes)',
 'tls.handshake.session_id_length.error': 'Label',
 'tls.handshake.session_ticket': 'Byte sequence',
 'tls.handshake.session_ticket_age_add': 'Unsigned integer (4 bytes)',
 'tls.handshake.session_ticket_length': 'Unsigned integer (2 bytes)',
 'tls.handshake.session_ticket_lifetime_hint': 'Unsigned integer (4 bytes)',
 'tls.handshake.session_ticket_nonce': 'Byte sequence',
 'tls.handshake.session_ticket_nonce_length': 'Unsigned integer (1 byte)',
 'tls.handshake.sha_hash': 'Label',
 'tls.handshake.sig': 'Byte sequence',
 'tls.handshake.sig_hash_alg': 'Unsigned integer (2 bytes)',
 'tls.handshake.sig_hash_alg_len': 'Unsigned integer (2 bytes)',
 'tls.handshake.sig_hash_algs': 'Label',
 'tls.handshake.sig_hash_hash': 'Unsigned integer (1 byte)',
 'tls.handshake.sig_hash_sig': 'Unsigned integer (1 byte)',
 'tls.handshake.sig_len': 'Unsigned integer (2 bytes)',
 'tls.handshake.status_request.undecoded': 'Label',
 'tls.handshake.type': 'Unsigned integer (1 byte)',
 'tls.handshake.vc': 'Byte sequence',
 'tls.handshake.vc_len': 'Unsigned integer (1 byte)',
 'tls.handshake.verify_data': 'Label',
 'tls.handshake.version': 'Unsigned integer (2 bytes)',
 'tls.handshake.vs': 'Byte sequence',
 'tls.handshake.vs_len': 'Unsigned integer (1 byte)',
 'tls.handshake.xc': 'Byte sequence',
 'tls.handshake.xc_len': 'Unsigned integer (1 byte)',
 'tls.handshake.xs': 'Byte sequence',
 'tls.handshake.xs_len': 'Unsigned integer (1 byte)',
 'tls.handshake.yc': 'Byte sequence',
 'tls.handshake.yc_len': 'Unsigned integer (2 bytes)',
 'tls.handshake.ys': 'Byte sequence',
 'tls.handshake.ys_len': 'Unsigned integer (2 bytes)',
 'tls.heartbeat_message': 'Label',
 'tls.heartbeat_message.padding': 'Byte sequence',
 'tls.heartbeat_message.payload': 'Byte sequence',
 'tls.heartbeat_message.payload_length': 'Unsigned integer (2 bytes)',
 'tls.heartbeat_message.payload_length.invalid': 'Label',
 'tls.heartbeat_message.type': 'Unsigned integer (1 byte)',
 'tls.ignored_unknown_record': 'Label',
 'tls.malformed.buffer_too_small': 'Label',
 'tls.malformed.trailing_data': 'Label',
 'tls.malformed.vector_length': 'Label',
 'tls.quic.initial_version': 'Unsigned integer (4 bytes)',
 'tls.quic.len': 'Unsigned integer (2 bytes)',
 'tls.quic.negotiated_version': 'Unsigned integer (4 bytes)',
 'tls.quic.parameter': 'Label',
 'tls.quic.parameter.ack_delay_exponent': 'Unsigned integer (8 bytes)',
 'tls.quic.parameter.active_connection_id_limit': 'Unsigned integer (8 bytes)',
 'tls.quic.parameter.cibir_encoding.length': 'Unsigned integer (8 bytes)',
 'tls.quic.parameter.cibir_encoding.offset': 'Unsigned integer (8 bytes)',
 'tls.quic.parameter.enable_time_stamp_v2': 'Unsigned integer (8 bytes)',
 'tls.quic.parameter.facebook.partial_reliability': 'Unsigned integer (8 bytes)',
 'tls.quic.parameter.google.connection_options': 'Byte sequence',
 'tls.quic.parameter.google.initial_rtt': 'Unsigned integer (8 bytes)',
 'tls.quic.parameter.google.key_update_not_yet_supported': 'Label',
 'tls.quic.parameter.google.quic_params': 'Byte sequence',
 'tls.quic.parameter.google.quic_params_unknown_field': 'Byte sequence',
 'tls.quic.parameter.google.quic_version': 'Unsigned integer (4 bytes)',
 'tls.quic.parameter.google.support_handshake_done': 'Label',
 'tls.quic.parameter.google.supported_version': 'Unsigned integer (4 bytes)',
 'tls.quic.parameter.google.supported_versions_length': 'Unsigned integer (1 byte)',
 'tls.quic.parameter.google.user_agent': 'Character string',
 'tls.quic.parameter.idle_timeout': 'Unsigned integer (8 bytes)',
 'tls.quic.parameter.initial_max_data': 'Unsigned integer (8 bytes)',
 'tls.quic.parameter.initial_max_stream_data_bidi_local': 'Unsigned integer (8 bytes)',
 'tls.quic.parameter.initial_max_stream_data_bidi_remote': 'Unsigned integer (8 bytes)',
 'tls.quic.parameter.initial_max_stream_data_uni': 'Unsigned integer (8 bytes)',
 'tls.quic.parameter.initial_max_streams_bidi': 'Unsigned integer (8 bytes)',
 'tls.quic.parameter.initial_max_streams_uni': 'Unsigned integer (8 bytes)',
 'tls.quic.parameter.initial_source_connection_id': 'Byte sequence',
 'tls.quic.parameter.lengt.old': 'Unsigned integer (2 bytes)',
 'tls.quic.parameter.length': 'Unsigned integer (8 bytes)',
 'tls.quic.parameter.loss_bits': 'Unsigned integer (8 bytes)',
 'tls.quic.parameter.max_ack_delay': 'Unsigned integer (8 bytes)',
 'tls.quic.parameter.max_datagram_frame_size': 'Unsigned integer (8 bytes)',
 'tls.quic.parameter.max_idle_timeout': 'Unsigned integer (8 bytes)',
 'tls.quic.parameter.max_packet_size': 'Unsigned integer (8 bytes)',
 'tls.quic.parameter.max_udp_payload_size': 'Unsigned integer (8 bytes)',
 'tls.quic.parameter.min_ack_delay': 'Unsigned integer (8 bytes)',
 'tls.quic.parameter.ocid': 'Byte sequence',
 'tls.quic.parameter.original_destination_connection_id': 'Byte sequence',
 'tls.quic.parameter.preferred_address.connectionid': 'Byte sequence',
 'tls.quic.parameter.preferred_address.connectionid.length': 'Unsigned integer (1 byte)',
 'tls.quic.parameter.preferred_address.ipaddress.length': 'Unsigned integer (1 byte)',
 'tls.quic.parameter.preferred_address.ipv4address': 'IPv4 address',
 'tls.quic.parameter.preferred_address.ipv4port': 'Unsigned integer (2 bytes)',
 'tls.quic.parameter.preferred_address.ipv6address': 'IPv6 address',
 'tls.quic.parameter.preferred_address.ipv6port': 'Unsigned integer (2 bytes)',
 'tls.quic.parameter.preferred_address.ipversion': 'Unsigned integer (1 byte)',
 'tls.quic.parameter.preferred_address.statelessresettoken': 'Byte sequence',
 'tls.quic.parameter.retry_source_connection_id': 'Byte sequence',
 'tls.quic.parameter.stateless_reset_token': 'Byte sequence',
 'tls.quic.parameter.type': 'Unsigned integer (8 bytes)',
 'tls.quic.parameter.value': 'Byte sequence',
 'tls.quic.parameter.vi.chosen_version': 'Unsigned integer (4 bytes)',
 'tls.quic.parameter.vi.other_version': 'Unsigned integer (4 bytes)',
 'tls.quic.parameter.vn.compatible_version': 'Unsigned integer (4 bytes)',
 'tls.quic.parameter.vn.compatible_version_count': 'Unsigned integer (8 bytes)',
 'tls.quic.parameter.vn.currently_attempted_version': 'Unsigned integer (4 bytes)',
 'tls.quic.parameter.vn.negotiated_version': 'Unsigned integer (4 bytes)',
 'tls.quic.parameter.vn.previously_attempted_version': 'Unsigned integer (4 bytes)',
 'tls.quic.parameter.vn.received_negotiation_version': 'Unsigned integer (4 bytes)',
 'tls.quic.parameter.vn.received_negotiation_version_count': 'Unsigned integer (8 bytes)',
 'tls.quic.parameter.vn.supported_version': 'Unsigned integer (4 bytes)',
 'tls.quic.parameter.vn.supported_version_count': 'Unsigned integer (8 bytes)',
 'tls.quic.supported_versions': 'Unsigned integer (4 bytes)',
 'tls.quic.supported_versions.len': 'Unsigned integer (2 bytes)',
 'tls.reassembled.data': 'Byte sequence',
 'tls.reassembled.length': 'Unsigned integer (4 bytes)',
 'tls.reassembled_in': 'Frame number',
 'tls.record': 'Label',
 'tls.record.content_type': 'Unsigned integer (1 byte)',
 'tls.record.is_escape': 'Boolean',
 'tls.record.length': 'Unsigned integer (2 bytes)',
 'tls.record.length.invalid': 'Label',
 'tls.record.opaque_type': 'Unsigned integer (1 byte)',
 'tls.record.padding_length': 'Unsigned integer (1 byte)',
 'tls.record.version': 'Unsigned integer (2 bytes)',
 'tls.record_size_limit': 'Unsigned integer (2 bytes)',
 'tls.resumed': 'Label',
 'tls.sct.sct_extensions': 'Label',
 'tls.sct.sct_extensions_length': 'Unsigned integer (2 bytes)',
 'tls.sct.sct_length': 'Unsigned integer (2 bytes)',
 'tls.sct.sct_logid': 'Byte sequence',
 'tls.sct.sct_signature': 'Byte sequence',
 'tls.sct.sct_signature_length': 'Unsigned integer (2 bytes)',
 'tls.sct.sct_timestamp': 'Date and time',
 'tls.sct.sct_version': 'Unsigned integer (1 byte)',
 'tls.sct.scts_length': 'Unsigned integer (2 bytes)',
 'tls.segment': 'Frame number',
 'tls.segment.count': 'Unsigned integer (4 bytes)',
 'tls.segment.data': 'Byte sequence',
 'tls.segment.error': 'Frame number',
 'tls.segment.multipletails': 'Boolean',
 'tls.segment.overlap': 'Boolean',
 'tls.segment.overlap.conflict': 'Boolean',
 'tls.segment.toolongfragment': 'Boolean',
 'tls.segments': 'Label',
 'tls.unexpected_message': 'Label',
 
 'http.prev_response_in': 'Frame number',
 'http.proxy_authenticate': 'Character string',
 'http.proxy_authorization': 'Character string',
 'http.proxy_connect_host': 'Character string',
 'http.proxy_connect_port': 'Unsigned integer, 2 bytes',
 'http.referer': 'Character string',
 'http.request': 'Boolean',
 'http.request.full_uri': 'Character string',
 'http.request.line': 'Character string',
 'http.request.method': 'Character string',
 'http.request.uri': 'Character string',
 'http.request.uri.path': 'Character string',
 'http.request.uri.query': 'Character string',
 'http.request.uri.query.parameter': 'Character string',
 'http.request.version': 'Character string',
 'http.request_in': 'Frame number',
 'http.request_number': 'Unsigned integer, 4 bytes',
 'http.response': 'Boolean',
 'http.response.code': 'Unsigned integer, 2 bytes',
 'http.response.code.desc': 'Character string',
 'http.response.line': 'Character string',
 'http.response.phrase': 'Character string',
 'http.response.version': 'Character string',
 'http.response_for.uri': 'Character string',
 'http.response_in': 'Frame number',
 'http.response_number': 'Unsigned integer, 4 bytes',
 'http.sec_websocket_accept': 'Character string',
 'http.sec_websocket_extensions': 'Character string',
 'http.sec_websocket_key': 'Character string',
 'http.sec_websocket_protocol': 'Character string',
 'http.sec_websocket_version': 'Character string',
 'http.server': 'Character string',
 'http.set_cookie': 'Character string',
 'http.ssl_port': 'Label',
 'http.subdissector_failed': 'Label',
 'http.te_and_length': 'Label',
 'http.te_unknown': 'Label',
 'http.time': 'Time offset',
 'http.tls_port': 'Label',
 'http.transfer_encoding': 'Character string',
 'http.unknown_header': 'Character string',
 'http.upgrade': 'Character string',
 'http.user_agent': 'Character string',
 'http.www_authenticate': 'Character string',
 'http.x_forwarded_for': 'Character string'}


wire_shark_description_lookup_map = {'comment': 'Comment',
 'frame.bblog': 'Black Box Log',
 'frame.bblog.serial_nr': 'Serial Number',
 'frame.bblog.ticks': 'Ticks',
 'frame.cap_len': 'Frame length stored into the capture file',
 'frame.cb_copy': 'Copying',
 'frame.cb_pen': 'Private Enterprise Number',
 'frame.coloring_rule.name': 'Coloring Rule Name',
 'frame.coloring_rule.string': 'Coloring Rule String',
 'frame.comment': 'Comment',
 'frame.comment.expert': 'Formatted comment',
 'frame.dlt': 'WTAP_ENCAP',
 'frame.drop_count': 'Drop Count',
 'frame.encap_type': 'Encapsulation type',
 'frame.file_off': 'File Offset',
 'frame.ignored': 'Frame is ignored',
 'frame.incomplete': 'Incomplete dissector',
 'frame.interface_description': 'Interface description',
 'frame.interface_id': 'Interface id',
 'frame.interface_name': 'Interface name',
 'frame.interface_queue': 'Interface queue',
 'frame.len': 'Frame length on the wire',
 'frame.len_lt_caplen': 'Frame length is less than captured length',
 'frame.link_nr': 'Link Number',
 'frame.marked': 'Frame is marked',
 'frame.md5_hash': 'Frame MD5 Hash',
 'frame.number': 'Frame Number',
 'frame.offset_shift': 'Time shift for this packet',
 'frame.p2p_dir': 'Point-to-Point Direction',
 'frame.p_prot_data': 'Number of per-protocol-data',
 'frame.packet_flags': 'Packet flags',
 'frame.packet_flags_crc_error': 'CRC error',
 'frame.packet_flags_direction': 'Direction',
 'frame.packet_flags_fcs_length': 'FCS length',
 'frame.packet_flags_packet_too_error': 'Packet too long error',
 'frame.packet_flags_packet_too_short_error': 'Packet too short error',
 'frame.packet_flags_preamble_error': 'Preamble error',
 'frame.packet_flags_reception_type': 'Reception type',
 'frame.packet_flags_reserved': 'Reserved',
 'frame.packet_flags_start_frame_delimiter_error': 'Start frame delimiter error',
 'frame.packet_flags_symbol_error': 'Symbol error',
 'frame.packet_flags_unaligned_frame_error': 'Unaligned frame error',
 'frame.packet_flags_wrong_inter_frame_gap_error': 'Wrong interframe gap error',
 'frame.packet_id': 'Packet id',
 'frame.pcaplog.data': 'Data',
 'frame.pcaplog.data_length': 'Data Length',
 'frame.pcaplog.data_type': 'Date Type',
 'frame.pkt_len': 'Frame length on the wire',
 'frame.protocols': 'Protocols in frame',
 'frame.ref_time': 'This is a Time Reference frame',
 'frame.section_number': 'Section number',
 'frame.time': 'Arrival Time',
 'frame.time_delta': 'Time delta from previous captured frame',
 'frame.time_delta_displayed': 'Time delta from previous displayed frame',
 'frame.time_epoch': 'Epoch Time',
 'frame.time_invalid': 'Arrival Time: Fractional second out of range (0-1000000000)',
 'frame.time_relative': 'Time since reference or first frame',
 'frame.verdict': 'Verdict',
 'frame.verdict.ebpf_tc': 'eBPF TC',
 'frame.verdict.ebpf_xdp': 'eBPF XDP',
 'frame.verdict.hw': 'Hardware',
 'frame.verdict.unknown': 'Unknown',
 'eth.addr': 'Address',
 'eth.addr.oui': 'Address OUI',
 'eth.addr.oui_resolved': 'Address OUI (resolved)',
 'eth.addr_resolved': 'Address (resolved)',
 'eth.dst': 'Destination',
 'eth.dst.ig': 'IG bit',
 'eth.dst.lg': 'LG bit',
 'eth.dst.oui': 'Destination OUI',
 'eth.dst.oui_resolved': 'Destination OUI (resolved)',
 'eth.dst_resolved': 'Destination (resolved)',
 'eth.fcs': 'Frame check sequence',
 'eth.fcs.status': 'FCS Status',
 'eth.fcs_bad': 'Bad checksum',
 'eth.fcs_bad.expert': 'Expert Info',
 'eth.fcs_good': 'FCS Good',
 'eth.ig': 'IG bit',
 'eth.invalid_lentype': 'Invalid length/type',
 'eth.invalid_lentype.expert': 'Invalid length/type',
 'eth.len': 'Length',
 'eth.len.past_end': 'Length field value goes past the end of the payload',
 'eth.lg': 'LG bit',
 'eth.padding': 'Padding',
 'eth.padding_bad': 'Padding identification may be inaccurate and impact trailer dissector',
 'eth.src': 'Source',
 'eth.src.ig': 'IG bit',
 'eth.src.lg': 'LG bit',
 'eth.src.oui': 'Source OUI',
 'eth.src.oui_resolved': 'Source OUI (resolved)',
 'eth.src_not_group': 'Source MAC must not be a group address: IEEE 802.3-2002, Section 3.2.3(b)',
 'eth.src_resolved': 'Source (resolved)',
 'eth.trailer': 'Trailer',
 'eth.type': 'Type',
 'eth.vlan.cfi': 'CFI',
 'eth.vlan.id': 'VLAN',
 'eth.vlan.pri': 'Priority',
 'eth.vlan.tpid': 'Identifier','ip.addr': 'Source or Destination Address',
 'ip.bogus_header_length': 'Bogus IP header length',
 'ip.bogus_ip_length': 'Bogus IP length',
 'ip.bogus_ip_version': 'Bogus IP version',
 'ip.checksum': 'Header Checksum',
 'ip.checksum.status': 'Header checksum status',
 'ip.checksum_bad': 'Bad',
 'ip.checksum_bad.expert': 'Bad checksum',
 'ip.checksum_calculated': 'Calculated Checksum',
 'ip.checksum_good': 'Good',
 'ip.cipso.categories': 'Categories',
 'ip.cipso.doi': 'DOI',
 'ip.cipso.malformed': 'Malformed CIPSO tag',
 'ip.cipso.sensitivity_level': 'Sensitivity Level',
 'ip.cipso.tag_data': 'Tag data',
 'ip.cipso.tag_type': 'Tag Type',
 'ip.cur_rt': 'Current Route',
 'ip.cur_rt_host': 'Current Route Host',
 'ip.dsfield': 'Differentiated Services Field',
 'ip.dsfield.ce': 'ECN-CE',
 'ip.dsfield.dscp': 'Differentiated Services Codepoint',
 'ip.dsfield.ecn': 'Explicit Congestion Notification',
 'ip.dsfield.ect': 'ECN-Capable Transport (ECT)',
 'ip.dst': 'Destination Address',
 'ip.dst_host': 'Destination Host',
 'ip.empty_rt': 'Empty Route',
 'ip.empty_rt_host': 'Empty Route Host',
 'ip.evil_packet': 'Packet has evil intent',
 'ip.flags': 'Flags',
 'ip.flags.df': "Don't fragment",
 'ip.flags.mf': 'More fragments',
 'ip.flags.rb': 'Reserved bit',
 'ip.flags.sf': 'Security flag',
 'ip.frag_offset': 'Fragment Offset',
 'ip.fragment': 'IPv4 Fragment',
 'ip.fragment.count': 'Fragment count',
 'ip.fragment.error': 'Defragmentation error',
 'ip.fragment.multipletails': 'Multiple tail fragments found',
 'ip.fragment.overlap': 'Fragment overlap',
 'ip.fragment.overlap.conflict': 'Conflicting data in fragment overlap',
 'ip.fragment.toolongfragment': 'Fragment too long',
 'ip.fragments': 'IPv4 Fragments',
 'ip.geoip.asnum': 'Source or Destination GeoIP AS Number',
 'ip.geoip.city': 'Source or Destination GeoIP City',
 'ip.geoip.country': 'Source or Destination GeoIP Country',
 'ip.geoip.country_iso': 'Source or Destination GeoIP ISO Two Letter Country Code',
 'ip.geoip.dst_asnum': 'Destination GeoIP AS Number',
 'ip.geoip.dst_city': 'Destination GeoIP City',
 'ip.geoip.dst_country': 'Destination GeoIP Country',
 'ip.geoip.dst_country_iso': 'Destination GeoIP ISO Two Letter Country Code',
 'ip.geoip.dst_isp': 'Destination GeoIP ISP',
 'ip.geoip.dst_lat': 'Destination GeoIP Latitude',
 'ip.geoip.dst_lon': 'Destination GeoIP Longitude',
 'ip.geoip.dst_org': 'Destination GeoIP AS Organization',
 'ip.geoip.dst_summary': 'Destination GeoIP',
 'ip.geoip.isp': 'Source or Destination GeoIP ISP',
 'ip.geoip.lat': 'Source or Destination GeoIP Latitude',
 'ip.geoip.lon': 'Source or Destination GeoIP Longitude',
 'ip.geoip.org': 'Source or Destination GeoIP AS Organization',
 'ip.geoip.src_asnum': 'Source GeoIP AS Number',
 'ip.geoip.src_city': 'Source GeoIP City',
 'ip.geoip.src_country': 'Source GeoIP Country',
 'ip.geoip.src_country_iso': 'Source GeoIP ISO Two Letter Country Code',
 'ip.geoip.src_isp': 'Source GeoIP ISP',
 'ip.geoip.src_lat': 'Source GeoIP Latitude',
 'ip.geoip.src_lon': 'Source GeoIP Longitude',
 'ip.geoip.src_org': 'Source GeoIP AS Organization',
 'ip.geoip.src_summary': 'Source GeoIP',
 'ip.hdr_len': 'Header Length',
 'ip.host': 'Source or Destination Host',
 'ip.id': 'Identification',
 'ip.len': 'Total Length',
 'ip.nop': '4 NOP in a row - a router may have removed some options',
 'ip.opt.addr': 'IP Address',
 'ip.opt.ext_sec_add_sec_info': 'Additional Security Info',
 'ip.opt.ext_sec_add_sec_info_format_code': 'Additional Security Info Format Code',
 'ip.opt.flag': 'Flag',
 'ip.opt.id_number': 'ID Number',
 'ip.opt.len': 'Length',
 'ip.opt.len.invalid': 'Invalid length for option',
 'ip.opt.mtu': 'MTU',
 'ip.opt.ohc': 'Outbound Hop Count',
 'ip.opt.originator': 'Originator IP Address',
 'ip.opt.overflow': 'Overflow',
 'ip.opt.padding': 'Padding',
 'ip.opt.ptr': 'Pointer',
 'ip.opt.ptr.before_address': 'Pointer points before first address',
 'ip.opt.ptr.middle_address': 'Pointer points to middle of address',
 'ip.opt.qs_func': 'Function',
 'ip.opt.qs_nonce': 'QS Nonce',
 'ip.opt.qs_rate': 'Rate',
 'ip.opt.qs_reserved': 'Reserved',
 'ip.opt.qs_ttl': 'QS TTL',
 'ip.opt.qs_ttl_diff': 'TTL Diff',
 'ip.opt.qs_unused': 'Not Used',
 'ip.opt.ra': 'Router Alert',
 'ip.opt.rhc': 'Return Hop Count',
 'ip.opt.sec_cl': 'Classification Level',
 'ip.opt.sec_prot_auth_doe': 'DOE',
 'ip.opt.sec_prot_auth_flags': 'Protection Authority Flags',
 'ip.opt.sec_prot_auth_fti': 'Field Termination Indicator',
 'ip.opt.sec_prot_auth_genser': 'GENSER',
 'ip.opt.sec_prot_auth_nsa': 'NSA',
 'ip.opt.sec_prot_auth_sci': 'SCI',
 'ip.opt.sec_prot_auth_siop_esi': 'SIOP-ESI',
 'ip.opt.sec_prot_auth_unassigned': 'Unassigned',
 'ip.opt.sec_rfc791_comp': 'Compartments',
 'ip.opt.sec_rfc791_hr': 'Handling Restrictions',
 'ip.opt.sec_rfc791_sec': 'Security',
 'ip.opt.sec_rfc791_tcc': 'Transmission Control Code',
 'ip.opt.sid': 'Stream Identifier',
 'ip.opt.time_stamp': 'Time stamp',
 'ip.opt.time_stamp_addr': 'Address',
 'ip.opt.type': 'Type',
 'ip.opt.type.class': 'Class',
 'ip.opt.type.copy': 'Copy on fragmentation',
 'ip.opt.type.number': 'Number',
 'ip.proto': 'Protocol',
 'ip.reassembled.data': 'Reassembled IPv4 data',
 'ip.reassembled.length': 'Reassembled IPv4 length',
 'ip.reassembled_in': 'Reassembled IPv4 in frame',
 'ip.rec_rt': 'Recorded Route',
 'ip.rec_rt_host': 'Recorded Route Host',
 'ip.src': 'Source Address',
 'ip.src_host': 'Source Host',
 'ip.src_rt': 'Source Route',
 'ip.src_rt_host': 'Source Route Host',
 'ip.subopt_too_long': 'Suboption would go past end of option',
 'ip.tos': 'Type of Service',
 'ip.tos.cost': 'Cost',
 'ip.tos.delay': 'Delay',
 'ip.tos.precedence': 'Precedence',
 'ip.tos.reliability': 'Reliability',
 'ip.tos.throughput': 'Throughput',
 'ip.ttl': 'Time to Live',
 'ip.ttl.lncb': 'Time To Live',
 'ip.ttl.too_small': 'Time To Live',
 'ip.version': 'Version',
 'mptcp.analysis.echoed_key_mismatch': 'Expert Info',
 'mptcp.analysis.missing_algorithm': 'Expert Info',
 'mptcp.analysis.unexpected_idsn': 'Expert Info',
 'mptcp.analysis.unsupported_algorithm': 'Expert Info',
 'mptcp.connection.echoed_key_mismatch': 'The echoed key in the ACK of the MPTCP handshake does not match the key of the SYN/ACK',
 'mptcp.connection.missing_algorithm': 'No crypto algorithm specified',
 'mptcp.connection.unsupported_algorithm': 'Unsupported algorithm',
 'mptcp.dss.infinite_mapping': 'Fallback to infinite mapping',
 'mptcp.dss.missing_mapping': 'No mapping available',
 'tcp.ack': 'Acknowledgment Number',
 'tcp.ack.nonzero': 'The acknowledgment number field is nonzero while the ACK flag is not set',
 'tcp.ack_raw': 'Acknowledgment number (raw)',
 'tcp.analysis': 'SEQ/ACK analysis',
 'tcp.analysis.ack_lost_segment': "ACKed segment that wasn't captured (common at capture start)",
 'tcp.analysis.ack_rtt': 'The RTT to ACK the segment was',
 'tcp.analysis.acks_frame': 'This is an ACK to the segment in frame',
 'tcp.analysis.bytes_in_flight': 'Bytes in flight',
 'tcp.analysis.duplicate_ack': 'Duplicate ACK',
 'tcp.analysis.duplicate_ack_frame': 'Duplicate to the ACK in frame',
 'tcp.analysis.duplicate_ack_num': 'Duplicate ACK #',
 'tcp.analysis.fast_retransmission': 'This frame is a (suspected) fast retransmission',
 'tcp.analysis.flags': 'TCP Analysis Flags',
 'tcp.analysis.initial_rtt': 'iRTT',
 'tcp.analysis.keep_alive': 'TCP keep-alive segment',
 'tcp.analysis.keep_alive_ack': 'ACK to a TCP keep-alive segment',
 'tcp.analysis.lost_segment': 'Previous segment(s) not captured (common at capture start)',
 'tcp.analysis.out_of_order': 'This frame is a (suspected) out-of-order segment',
 'tcp.analysis.push_bytes_sent': 'Bytes sent since last PSH flag',
 'tcp.analysis.retransmission': 'This frame is a (suspected) retransmission',
 'tcp.analysis.reused_ports': 'A new tcp session is started with the same ports as an earlier session in this trace',
 'tcp.analysis.rto': 'The RTO for this segment was',
 'tcp.analysis.rto_frame': 'RTO based on delta from frame',
 'tcp.analysis.spurious_retransmission': 'This frame is a (suspected) spurious retransmission',
 'tcp.analysis.tfo_ack': 'TCP SYN-ACK accepting TFO data',
 'tcp.analysis.tfo_ignored': 'TCP SYN-ACK ignoring TFO data',
 'tcp.analysis.tfo_syn': 'TCP SYN with TFO Cookie',
 'tcp.analysis.window_full': 'TCP window specified by the receiver is now completely full',
 'tcp.analysis.window_update': 'TCP window update',
 'tcp.analysis.zero_window': 'TCP Zero Window segment',
 'tcp.analysis.zero_window_probe': 'TCP Zero Window Probe',
 'tcp.analysis.zero_window_probe_ack': 'ACK to a TCP Zero Window Probe',
 'tcp.bogus_header_length': 'Bogus TCP Header length',
 'tcp.checksum': 'Checksum',
 'tcp.checksum.ffff': 'TCP Checksum 0xffff instead of 0x0000 (see RFC 1624)',
 'tcp.checksum.status': 'Checksum Status',
 'tcp.checksum_bad': 'Bad Checksum',
 'tcp.checksum_bad.expert': 'Bad checksum',
 'tcp.checksum_calculated': 'Calculated Checksum',
 'tcp.checksum_good': 'Good Checksum',
 'tcp.completeness': 'Conversation completeness',
 'tcp.connection.fin': 'Connection finish (FIN)',
 'tcp.connection.fin_active': 'This frame initiates the connection closing',
 'tcp.connection.fin_passive': 'This frame undergoes the connection closing',
 'tcp.connection.rst': 'Connection reset (RST)',
 'tcp.connection.sack': 'Connection establish acknowledge (SYN+ACK)',
 'tcp.connection.syn': 'Connection establish request (SYN)',
 'tcp.connection.synack': 'Connection establish acknowledge (SYN+ACK)',
 'tcp.continuation_to': 'This is a continuation to the PDU in frame',
 'tcp.data': 'TCP segment data',
 'tcp.dstport': 'Destination Port',
 'tcp.fin_retransmission': 'Retransmission of FIN from frame',
 'tcp.flags': 'Flags',
 'tcp.flags.ace': 'ACE',
 'tcp.flags.ack': 'Acknowledgment',
 'tcp.flags.ae': 'Accurate ECN',
 'tcp.flags.cwr': 'Congestion Window Reduced',
 'tcp.flags.ece': 'ECN-Echo',
 'tcp.flags.ecn': 'ECN-Echo',
 'tcp.flags.fin': 'Fin',
 'tcp.flags.ns': 'Nonce',
 'tcp.flags.push': 'Push',
 'tcp.flags.res': 'Reserved',
 'tcp.flags.reset': 'Reset',
 'tcp.flags.str': 'TCP Flags',
 'tcp.flags.syn': 'Syn',
 'tcp.flags.urg': 'Urgent',
 'tcp.hdr_len': 'Header Length',
 'tcp.len': 'TCP Segment Len',
 'tcp.non_zero_bytes_after_eol': 'Non zero bytes in option space after EOL option',
 'tcp.nop': '4 NOP in a row - a router may have removed some options',
 'tcp.nxtseq': 'Next Sequence Number',
 'tcp.option.len.invalid': 'Invalid length for option',
 'tcp.option_kind': 'Kind',
 'tcp.option_len': 'Length',
 'tcp.options': 'TCP Options',
 'tcp.options.acc_ecn.eceb': 'Accurate ECN Echo CE Byte Counter',
 'tcp.options.acc_ecn.ee0b': 'Accurate ECN Echo ECT(0) Byte Counter',
 'tcp.options.acc_ecn.ee1b': 'Accurate ECN Echo ECT(1) Byte Counter',
 'tcp.options.ao.keyid': 'AO KeyID',
 'tcp.options.ao.mac': 'AO MAC',
 'tcp.options.ao.rnextkeyid': 'AO RNextKeyID',
 'tcp.options.cc': 'TCP CC Option',
 'tcp.options.cc_value': 'TCP CC Option',
 'tcp.options.ccecho': 'TCP CC Echo Option',
 'tcp.options.ccnew': 'TCP CC New Option',
 'tcp.options.echo': 'TCP Echo Option',
 'tcp.options.echo_reply': 'TCP Echo Reply Option',
 'tcp.options.echo_value': 'TCP Echo Option',
 'tcp.options.experimental': 'TCP Option - Experimental',
 'tcp.options.experimental.data': 'Data',
 'tcp.options.experimental.exid': 'Experiment Identifier',
 'tcp.options.experimental.magic_number': 'Magic Number',
 'tcp.options.md5': 'TCP MD5 Option',
 'tcp.options.md5.digest': 'MD5 digest',
 'tcp.options.mood': 'TCP Mood Option',
 'tcp.options.mood_val': 'TCP Mood Option Value',
 'tcp.options.mptcp.addaddrtrunchmac': 'Truncated HMAC',
 'tcp.options.mptcp.addrid': 'Address ID',
 'tcp.options.mptcp.backup.flag': 'Backup flag',
 'tcp.options.mptcp.checksum': 'Checksum',
 'tcp.options.mptcp.checksumreq.flags': 'Checksum required',
 'tcp.options.mptcp.dataack': 'Multipath TCP Data ACK',
 'tcp.options.mptcp.dataack8.flag': 'Data ACK is 8 octets',
 'tcp.options.mptcp.dataackpresent.flag': 'Data ACK is present',
 'tcp.options.mptcp.datafin.flag': 'DATA_FIN',
 'tcp.options.mptcp.datalvllen': 'Data-level Length',
 'tcp.options.mptcp.dataseqno': 'Multipath TCP Data Sequence Number',
 'tcp.options.mptcp.dseqn8.flag': 'Data Sequence Number is 8 octets',
 'tcp.options.mptcp.dseqnpresent.flag': 'Data Sequence Number, Subflow Sequence Number, Data-level Length, Checksum present',
 'tcp.options.mptcp.echo': 'Echo',
 'tcp.options.mptcp.extensibility.flag': 'Extensibility',
 'tcp.options.mptcp.flag_T.flag': 'Transient',
 'tcp.options.mptcp.flag_U.flag': 'Flag U',
 'tcp.options.mptcp.flag_V.flag': 'Flag V',
 'tcp.options.mptcp.flag_W.flag': 'Flag W',
 'tcp.options.mptcp.flags': 'Multipath TCP flags',
 'tcp.options.mptcp.ipv4': 'Advertised IPv4 Address',
 'tcp.options.mptcp.ipv6': 'Advertised IPv6 Address',
 'tcp.options.mptcp.ipver': 'IP version',
 'tcp.options.mptcp.nomoresubflows.flag': 'Do not attempt to establish new subflows to this address and port',
 'tcp.options.mptcp.port': 'Advertised port',
 'tcp.options.mptcp.rawdataack': 'Original MPTCP Data ACK',
 'tcp.options.mptcp.rawdataseqno': 'Data Sequence Number',
 'tcp.options.mptcp.recvkey': "Receiver's Key",
 'tcp.options.mptcp.recvtok': "Receiver's Token",
 'tcp.options.mptcp.reserved': 'Reserved',
 'tcp.options.mptcp.reserved.flag': 'Reserved',
 'tcp.options.mptcp.rst_reason': 'TCPRST Reason',
 'tcp.options.mptcp.sendhmac': "Sender's HMAC",
 'tcp.options.mptcp.sendkey': "Sender's Key",
 'tcp.options.mptcp.sendmac': "Multipath TCP Sender's MAC",
 'tcp.options.mptcp.sendrand': "Sender's Random Number",
 'tcp.options.mptcp.sendtrunchmac': "Sender's Truncated HMAC",
 'tcp.options.mptcp.sendtruncmac': "Multipath TCP Sender's Truncated MAC",
 'tcp.options.mptcp.sha1.flag': 'Use HMAC-SHA1',
 'tcp.options.mptcp.sha256.flag': 'Use HMAC-SHA256',
 'tcp.options.mptcp.subflowseqno': 'Subflow Sequence Number',
 'tcp.options.mptcp.subtype': 'Multipath TCP subtype',
 'tcp.options.mptcp.version': 'Multipath TCP version',
 'tcp.options.mss': 'TCP MSS Option',
 'tcp.options.mss.absent': 'The SYN packet does not contain a MSS option',
 'tcp.options.mss.present': 'The non-SYN packet does contain a MSS option',
 'tcp.options.mss_val': 'MSS Value',
 'tcp.options.qs': 'TCP QS Option',
 'tcp.options.qs.rate': 'QS Rate',
 'tcp.options.qs.ttl_diff': 'QS Rate',
 'tcp.options.rvbd.probe': 'Riverbed Probe',
 'tcp.options.rvbd.probe.appli_ver': 'Application Version',
 'tcp.options.rvbd.probe.client.ip': 'Client IP',
 'tcp.options.rvbd.probe.flags': 'Probe Flags',
 'tcp.options.rvbd.probe.flags.last': 'Last Notify',
 'tcp.options.rvbd.probe.flags.notcfe': 'Not CFE',
 'tcp.options.rvbd.probe.flags.probe': 'Disable Probe Cache on CSH',
 'tcp.options.rvbd.probe.flags.server': 'SSH outer to server established',
 'tcp.options.rvbd.probe.flags.ssl': 'SSL Enabled',
 'tcp.options.rvbd.probe.len': 'Length',
 'tcp.options.rvbd.probe.prober': 'CSH IP',
 'tcp.options.rvbd.probe.proxy.ip': 'SSH IP',
 'tcp.options.rvbd.probe.proxy.port': 'SSH Port',
 'tcp.options.rvbd.probe.reserved': 'Reserved',
 'tcp.options.rvbd.probe.storeid': 'CFE Store ID',
 'tcp.options.rvbd.probe.type1': 'Type',
 'tcp.options.rvbd.probe.type2': 'Type',
 'tcp.options.rvbd.probe.version': 'Version',
 'tcp.options.rvbd.probe.version_raw': 'Version',
 'tcp.options.rvbd.trpy': 'Riverbed Transparency',
 'tcp.options.rvbd.trpy.client.port': 'Out of band connection Client Port',
 'tcp.options.rvbd.trpy.dst.ip': 'Dst SH IP Addr',
 'tcp.options.rvbd.trpy.dst.port': 'Dst SH Inner Port',
 'tcp.options.rvbd.trpy.flags': 'Transparency Options',
 'tcp.options.rvbd.trpy.flags.chksum': 'Reserved',
 'tcp.options.rvbd.trpy.flags.fw_rst': 'Enable Transparency FW feature on All FWs',
 'tcp.options.rvbd.trpy.flags.fw_rst_inner': 'Enable Inner FW feature on All FWs',
 'tcp.options.rvbd.trpy.flags.fw_rst_probe': 'Enable FW traversal feature',
 'tcp.options.rvbd.trpy.flags.mode': 'Transparency Mode',
 'tcp.options.rvbd.trpy.flags.oob': 'Out of band connection',
 'tcp.options.rvbd.trpy.src.ip': 'Src SH IP Addr',
 'tcp.options.rvbd.trpy.src.port': 'Src SH Inner Port',
 'tcp.options.sack': 'TCP SACK Option',
 'tcp.options.sack.count': 'TCP SACK Count',
 'tcp.options.sack.dsack': 'D-SACK Sequence',
 'tcp.options.sack.dsack_le': 'TCP D-SACK Left Edge',
 'tcp.options.sack.dsack_re': 'TCP D-SACK Right Edge',
 'tcp.options.sack_le': 'TCP SACK Left Edge',
 'tcp.options.sack_perm': 'TCP SACK Permitted Option',
 'tcp.options.sack_re': 'TCP SACK Right Edge',
 'tcp.options.scps': 'TCP SCPS Capabilities Option',
 'tcp.options.scps.binding': 'Connection ID',
 'tcp.options.scps.binding.data': 'Binding Space Data',
 'tcp.options.scps.binding.id': 'Binding Space (Community) ID',
 'tcp.options.scps.binding.len': 'Extended Capability Length',
 'tcp.options.scps.vector': 'TCP SCPS Capabilities Vector',
 'tcp.options.scpsflags.bets': 'Partial Reliability Capable (BETS)',
 'tcp.options.scpsflags.compress': 'Lossless Header Compression (COMP)',
 'tcp.options.scpsflags.nlts': 'Network Layer Timestamp (NLTS)',
 'tcp.options.scpsflags.reserved': 'Reserved',
 'tcp.options.scpsflags.reserved1': 'Reserved Bit 1',
 'tcp.options.scpsflags.reserved2': 'Reserved Bit 2',
 'tcp.options.scpsflags.reserved3': 'Reserved Bit 3',
 'tcp.options.scpsflags.snack1': 'Short Form SNACK Capable (SNACK1)',
 'tcp.options.scpsflags.snack2': 'Long Form SNACK Capable (SNACK2)',
 'tcp.options.snack': 'TCP Selective Negative Acknowledgment Option',
 'tcp.options.snack.le': 'TCP SNACK Left Edge',
 'tcp.options.snack.offset': 'TCP SNACK Offset',
 'tcp.options.snack.re': 'TCP SNACK Right Edge',
 'tcp.options.snack.sequence': 'SNACK Sequence',
 'tcp.options.snack.size': 'TCP SNACK Size',
 'tcp.options.tar.reserved': 'TARR Reserved',
 'tcp.options.tarr.rate': 'TARR Rate',
 'tcp.options.tfo': 'Fast Open Cookie',
 'tcp.options.tfo.cookie': 'Fast Open Cookie',
 'tcp.options.tfo.request': 'Fast Open Cookie Request',
 'tcp.options.time_stamp': 'TCP Time Stamp Option',
 'tcp.options.timestamp.tsecr': 'Timestamp echo reply',
 'tcp.options.timestamp.tsval': 'Timestamp value',
 'tcp.options.timestamp.tsval.syncookie.ecn': 'SYN Cookie ECN',
 'tcp.options.timestamp.tsval.syncookie.sack': 'SYN Cookie SACK',
 'tcp.options.timestamp.tsval.syncookie.timestamp': 'SYN Cookie Timestamp',
 'tcp.options.timestamp.tsval.syncookie.wscale': 'SYN Cookie WScale',
 'tcp.options.type': 'Type',
 'tcp.options.type.class': 'Class',
 'tcp.options.type.copy': 'Copy on fragmentation',
 'tcp.options.type.number': 'Number',
 'tcp.options.unknown.payload': 'Payload',
 'tcp.options.user_to': 'TCP User Timeout',
 'tcp.options.user_to_granularity': 'Granularity',
 'tcp.options.user_to_val': 'User Timeout',
 'tcp.options.wscale': 'TCP Window Scale Option',
 'tcp.options.wscale.multiplier': 'Multiplier',
 'tcp.options.wscale.shift': 'Shift count',
 'tcp.options.wscale.shift.invalid': 'Window scale shift exceeds 14',
 'tcp.options.wscale_val': 'TCP Windows Scale Option Value',
 'tcp.payload': 'TCP payload',
 'tcp.pdu.last_frame': 'Last frame of this PDU',
 'tcp.pdu.size': 'PDU Size',
 'tcp.pdu.time': 'Time until the last segment of this PDU',
 'tcp.port': 'Source or Destination Port',
 'tcp.proc.dstcmd': 'Destination process name',
 'tcp.proc.dstpid': 'Destination process ID',
 'tcp.proc.dstuid': 'Destination process user ID',
 'tcp.proc.dstuname': 'Destination process user name',
 'tcp.proc.srccmd': 'Source process name',
 'tcp.proc.srcpid': 'Source process ID',
 'tcp.proc.srcuid': 'Source process user ID',
 'tcp.proc.srcuname': 'Source process user name',
 'tcp.reassembled.data': 'Reassembled TCP Data',
 'tcp.reassembled.length': 'Reassembled TCP length',
 'tcp.reassembled_in': 'Reassembled PDU in frame',
 'tcp.reset_cause': 'Reset cause',
 'tcp.segment': 'TCP Segment',
 'tcp.segment.count': 'Segment count',
 'tcp.segment.error': 'Reassembling error',
 'tcp.segment.multipletails': 'Multiple tail segments found',
 'tcp.segment.overlap': 'Segment overlap',
 'tcp.segment.overlap.conflict': 'Conflicting data in segment overlap',
 'tcp.segment.toolongfragment': 'Segment too long',
 'tcp.segment_data': 'TCP segment data',
 'tcp.segments': 'Reassembled TCP Segments',
 'tcp.seq': 'Sequence Number',
 'tcp.seq_raw': 'Sequence Number (raw)',
 'tcp.short_segment': 'Short segment',
 'tcp.srcport': 'Source Port',
 'tcp.stream': 'Stream index',
 'tcp.suboption_malformed': 'suboption would go past end of option',
 'tcp.syncookie.hash': 'SYN Cookie hash',
 'tcp.syncookie.mss': 'SYN Cookie Maximum Segment Size',
 'tcp.syncookie.time': 'SYN Cookie Time',
 'tcp.time_delta': 'Time since previous frame in this TCP stream',
 'tcp.time_relative': 'Time since first frame in this TCP stream',
 'tcp.urgent_pointer': 'Urgent Pointer',
 'tcp.urgent_pointer.non_zero': 'The urgent pointer field is nonzero while the URG flag is not set',
 'tcp.window_size': 'Calculated window size',
 'tcp.window_size_scalefactor': 'Window size scaling factor',
 'tcp.window_size_value': 'Window',
 'tls.alert_message': 'Alert Message',
 'tls.alert_message.desc': 'Description',
 'tls.alert_message.level': 'Level',
 'tls.app_data': 'Encrypted Application Data',
 'tls.app_data_proto': 'Application Data Protocol',
 'tls.change_cipher_spec': 'Change Cipher Spec Message',
 'tls.compress_certificate.algorithm': 'Algorithm',
 'tls.compress_certificate.algorithms_length': 'Algorithms Length',
 'tls.compress_certificate.compressed_certificate_message': 'Compressed Certificate Message',
 'tls.compress_certificate.compressed_certificate_message.length': 'Length',
 'tls.compress_certificate.uncompressed_length': 'Uncompressed Length',
 'tls.connection_id': 'Connection ID',
 'tls.connection_id_length': 'Connection ID length',
 'tls.decompression_error': 'Decompression error',
 'tls.early_data.max_early_data_size': 'Maximum Early Data Size',
 'tls.esni.encrypted_sni': 'Encrypted SNI',
 'tls.esni.encrypted_sni_length': 'Encrypted SNI Length',
 'tls.esni.nonce': 'Nonce',
 'tls.esni.record_digest': 'Record Digest',
 'tls.esni.record_digest_length': 'Record Digest Length',
 'tls.esni.suite': 'Cipher Suite',
 'tls.extension.oid_filters.oid': 'Certificate Extension OID',
 'tls.extension.oid_filters.oid_length': 'Certificate Extension OID Length',
 'tls.extension.oid_filters.values_length': 'Certificate Extension Values Length',
 'tls.extension.oid_filters_length': 'OID Filters Length',
 'tls.extension.psk_ke_mode': 'PSK Key Exchange Mode',
 'tls.extension.psk_ke_modes_length': 'PSK Key Exchange Modes Length',
 'tls.handshake': 'Handshake Protocol',
 'tls.handshake.cert_type': 'Certificate Type',
 'tls.handshake.cert_type.type': 'Certificate Type',
 'tls.handshake.cert_type.types': 'Certificate Type List',
 'tls.handshake.cert_type.types_len': 'Certificate Type List Length',
 'tls.handshake.cert_types': 'Certificate types',
 'tls.handshake.cert_types_count': 'Certificate types count',
 'tls.handshake.cert_url.padding': 'Padding',
 'tls.handshake.cert_url.sha1': 'SHA1 Hash',
 'tls.handshake.cert_url.url': 'URL',
 'tls.handshake.cert_url.url_hash': 'URL and Hash',
 'tls.handshake.cert_url.url_hash_len': 'URL and Hash list Length',
 'tls.handshake.cert_url.url_len': 'URL Length',
 'tls.handshake.cert_url_type': 'Certificate Chain Type',
 'tls.handshake.certificate': 'Certificate',
 'tls.handshake.certificate_length': 'Certificate Length',
 'tls.handshake.certificate_request_context': 'Certificate Request Context',
 'tls.handshake.certificate_request_context_length': 'Certificate Request Context Length',
 'tls.handshake.certificates': 'Certificates',
 'tls.handshake.certificates_length': 'Certificates Length',
 'tls.handshake.challenge': 'Challenge',
 'tls.handshake.challenge_length': 'Challenge Length',
 'tls.handshake.cipher_spec_len': 'Cipher Spec Length',
 'tls.handshake.cipher_suites_length': 'Cipher Suites Length',
 'tls.handshake.cipherspec': 'Cipher Spec',
 'tls.handshake.ciphersuite': 'Cipher Suite',
 'tls.handshake.ciphersuites': 'Cipher Suites',
 'tls.handshake.clear_key_data': 'Clear Key Data',
 'tls.handshake.clear_key_length': 'Clear Key Data Length',
 'tls.handshake.client_cert_vrfy.sig': 'Signature',
 'tls.handshake.client_cert_vrfy.sig_len': 'Signature length',
 'tls.handshake.client_point': 'Pubkey',
 'tls.handshake.client_point_len': 'Pubkey Length',
 'tls.handshake.comp_method': 'Compression Method',
 'tls.handshake.comp_methods': 'Compression Methods',
 'tls.handshake.comp_methods_length': 'Compression Methods Length',
 'tls.handshake.connection_id': 'Connection ID',
 'tls.handshake.connection_id_length': 'Connection ID Length',
 'tls.handshake.cred.pubkey': 'Subject Public Key Info',
 'tls.handshake.cred.pubkey_len': 'Subject Public Key Info Length',
 'tls.handshake.cred.signature': 'Signature',
 'tls.handshake.cred.signature_len': 'Signature Length',
 'tls.handshake.cred.valid_time': 'Valid Time',
 'tls.handshake.dname': 'Distinguished Name',
 'tls.handshake.dname_len': 'Distinguished Name Length',
 'tls.handshake.dnames': 'Distinguished Names',
 'tls.handshake.dnames_len': 'Distinguished Names Length',
 'tls.handshake.dnames_truncated': 'Tree view truncated',
 'tls.handshake.encrypted_key': 'Encrypted Key',
 'tls.handshake.encrypted_key_length': 'Encrypted Key Data Length',
 'tls.handshake.epms': 'Encrypted PreMaster',
 'tls.handshake.epms_len': 'Encrypted PreMaster length',
 'tls.handshake.exponent': 'Exponent',
 'tls.handshake.exponent_len': 'Exponent Length',
 'tls.handshake.extension.data': 'Data',
 'tls.handshake.extension.heartbeat.mode': 'Mode',
 'tls.handshake.extension.len': 'Length',
 'tls.handshake.extension.type': 'Type',
 'tls.handshake.extensions.cookie': 'Cookie',
 'tls.handshake.extensions.cookie_len': 'Cookie length',
 'tls.handshake.extensions.psk.binders': 'PSK Binders',
 'tls.handshake.extensions.psk.binders_len': 'PSK Binders length',
 'tls.handshake.extensions.psk.identities.length': 'Identities Length',
 'tls.handshake.extensions.psk.identity.identity': 'Identity',
 'tls.handshake.extensions.psk.identity.identity_length': 'Identity Length',
 'tls.handshake.extensions.psk.identity.obfuscated_ticket_age': 'Obfuscated Ticket Age',
 'tls.handshake.extensions.psk.identity.selected': 'Selected Identity',
 'tls.handshake.extensions.supported_version': 'Supported Version',
 'tls.handshake.extensions.supported_versions_len': 'Supported Versions length',
 'tls.handshake.extensions_alpn_len': 'ALPN Extension Length',
 'tls.handshake.extensions_alpn_list': 'ALPN Protocol',
 'tls.handshake.extensions_alpn_str': 'ALPN Next Protocol',
 'tls.handshake.extensions_alpn_str_len': 'ALPN string length',
 'tls.handshake.extensions_alps.settings': 'ALPN Opaque Settings',
 'tls.handshake.extensions_alps_alpn_list': 'Supported ALPN List',
 'tls.handshake.extensions_alps_alpn_str': 'Supported ALPN',
 'tls.handshake.extensions_alps_alpn_str_len': 'Supported ALPN Length',
 'tls.handshake.extensions_alps_len': 'ALPS Extension Length',
 'tls.handshake.extensions_ec_point_format': 'EC point format',
 'tls.handshake.extensions_ec_point_formats': 'EC point formats',
 'tls.handshake.extensions_ec_point_formats_length': 'EC point formats Length',
 'tls.handshake.extensions_key_share_client_length': 'Client Key Share Length',
 'tls.handshake.extensions_key_share_group': 'Group',
 'tls.handshake.extensions_key_share_key_exchange': 'Key Exchange',
 'tls.handshake.extensions_key_share_key_exchange_length': 'Key Exchange Length',
 'tls.handshake.extensions_key_share_selected_group': 'Selected Group',
 'tls.handshake.extensions_length': 'Extensions Length',
 'tls.handshake.extensions_npn': 'Next Protocol',
 'tls.handshake.extensions_npn_str_len': 'Protocol string length',
 'tls.handshake.extensions_padding_data': 'Padding Data',
 'tls.handshake.extensions_reneg_info': 'Renegotiation info',
 'tls.handshake.extensions_reneg_info_len': 'Renegotiation info extension length',
 'tls.handshake.extensions_server_name': 'Server Name',
 'tls.handshake.extensions_server_name_len': 'Server Name length',
 'tls.handshake.extensions_server_name_list_len': 'Server Name list length',
 'tls.handshake.extensions_server_name_type': 'Server Name Type',
 'tls.handshake.extensions_srp_len': 'SRP username length',
 'tls.handshake.extensions_srp_username': 'SRP username',
 'tls.handshake.extensions_status_request_exts_len': 'Request Extensions Length',
 'tls.handshake.extensions_status_request_len': 'Certificate Status Length',
 'tls.handshake.extensions_status_request_list_len': 'Certificate Status List Length',
 'tls.handshake.extensions_status_request_responder_ids_len': 'Responder ID list Length',
 'tls.handshake.extensions_status_request_type': 'Certificate Status Type',
 'tls.handshake.extensions_supported_group': 'Supported Group',
 'tls.handshake.extensions_supported_groups': 'Supported Groups List',
 'tls.handshake.extensions_supported_groups_length': 'Supported Groups List Length',
 'tls.handshake.fragment': 'Handshake Fragment',
 'tls.handshake.fragment.count': 'Handshake Fragment count',
 'tls.handshake.fragments': 'Reassembled Handshake Fragments',
 'tls.handshake.g': 'g',
 'tls.handshake.g_len': 'g Length',
 'tls.handshake.hint': 'Hint',
 'tls.handshake.hint_len': 'Hint Length',
 'tls.handshake.identity': 'Identity',
 'tls.handshake.identity_len': 'Identity Length',
 'tls.handshake.ja3': 'JA3',
 'tls.handshake.ja3_full': 'JA3 Fullstring',
 'tls.handshake.ja3s': 'JA3S',
 'tls.handshake.ja3s_full': 'JA3S Fullstring',
 'tls.handshake.key_arg': 'Key Argument',
 'tls.handshake.key_arg_length': 'Key Argument Length',
 'tls.handshake.key_update.request_update': 'Key Update Request',
 'tls.handshake.length': 'Length',
 'tls.handshake.max_fragment_length': 'Maximum Fragment Length',
 'tls.handshake.md5_hash': 'MD5 Hash',
 'tls.handshake.modulus': 'Modulus',
 'tls.handshake.modulus_len': 'Modulus Length',
 'tls.handshake.npn_padding': 'Padding',
 'tls.handshake.npn_padding_len': 'Padding Length',
 'tls.handshake.npn_selected_protocol': 'Selected Protocol',
 'tls.handshake.npn_selected_protocol_len': 'Selected Protocol Length',
 'tls.handshake.ocsp_response_len': 'OCSP Response Length',
 'tls.handshake.ocsp_response_list_len': 'OCSP Response List Length',
 'tls.handshake.p': 'p',
 'tls.handshake.p_len': 'p Length',
 'tls.handshake.random': 'Random',
 'tls.handshake.random_bytes': 'Random Bytes',
 'tls.handshake.random_time': 'GMT Unix Time',
 'tls.handshake.rc': 'Schnorr signature',
 'tls.handshake.rc_len': 'Schnorr signature Length',
 'tls.handshake.reassembled_in': 'Reassembled Handshake Message in frame',
 'tls.handshake.rs': 'Schnorr signature',
 'tls.handshake.rs_len': 'Schnorr signature Length',
 'tls.handshake.server_curve_type': 'Curve Type',
 'tls.handshake.server_named_curve': 'Named Curve',
 'tls.handshake.server_point': 'Pubkey',
 'tls.handshake.server_point_len': 'Pubkey Length',
 'tls.handshake.session_id': 'Session ID',
 'tls.handshake.session_id_hit': 'Session ID Hit',
 'tls.handshake.session_id_length': 'Session ID Length',
 'tls.handshake.session_id_length.error': 'Session ID length error',
 'tls.handshake.session_ticket': 'Session Ticket',
 'tls.handshake.session_ticket_age_add': 'Session Ticket Age Add',
 'tls.handshake.session_ticket_length': 'Session Ticket Length',
 'tls.handshake.session_ticket_lifetime_hint': 'Session Ticket Lifetime Hint',
 'tls.handshake.session_ticket_nonce': 'Session Ticket Nonce',
 'tls.handshake.session_ticket_nonce_length': 'Session Ticket Nonce Length',
 'tls.handshake.sha_hash': 'SHA-1 Hash',
 'tls.handshake.sig': 'Signature',
 'tls.handshake.sig_hash_alg': 'Signature Algorithm',
 'tls.handshake.sig_hash_alg_len': 'Signature Hash Algorithms Length',
 'tls.handshake.sig_hash_algs': 'Signature Algorithms',
 'tls.handshake.sig_hash_hash': 'Signature Hash Algorithm Hash',
 'tls.handshake.sig_hash_sig': 'Signature Hash Algorithm Signature',
 'tls.handshake.sig_len': 'Signature Length',
 'tls.handshake.status_request.undecoded': 'Responder ID list or Request Extensions are not implemented, contact Wireshark developers if you want this to be supported',
 'tls.handshake.type': 'Handshake Message Type',
 'tls.handshake.vc': 'Ephemeral Pubkey',
 'tls.handshake.vc_len': 'Ephemeral Pubkey Length',
 'tls.handshake.verify_data': 'Verify Data',
 'tls.handshake.version': 'Version',
 'tls.handshake.vs': 'Ephemeral Pubkey',
 'tls.handshake.vs_len': 'Ephemeral Pubkey Length',
 'tls.handshake.xc': 'Pubkey',
 'tls.handshake.xc_len': 'Pubkey Length',
 'tls.handshake.xs': 'Pubkey',
 'tls.handshake.xs_len': 'Pubkey Length',
 'tls.handshake.yc': 'Pubkey',
 'tls.handshake.yc_len': 'Pubkey Length',
 'tls.handshake.ys': 'Pubkey',
 'tls.handshake.ys_len': 'Pubkey Length',
 'tls.heartbeat_message': 'Heartbeat Message',
 'tls.heartbeat_message.padding': 'Payload Length',
 'tls.heartbeat_message.payload': 'Payload Length',
 'tls.heartbeat_message.payload_length': 'Payload Length',
 'tls.heartbeat_message.payload_length.invalid': 'Invalid heartbeat payload length',
 'tls.heartbeat_message.type': 'Type',
 'tls.ignored_unknown_record': 'Ignored Unknown Record',
 'tls.malformed.buffer_too_small': 'Malformed message, not enough data is available',
 'tls.malformed.trailing_data': 'Undecoded trailing data is present',
 'tls.malformed.vector_length': 'Variable vector length is outside the permitted range',
 'tls.quic.initial_version': 'Initial Version',
 'tls.quic.len': 'Parameters Length',
 'tls.quic.negotiated_version': 'Negotiated Version',
 'tls.quic.parameter': 'Parameter',
 'tls.quic.parameter.ack_delay_exponent': 'ack_delay_exponent',
 'tls.quic.parameter.active_connection_id_limit': 'Active Connection ID Limit',
 'tls.quic.parameter.cibir_encoding.length': 'length',
 'tls.quic.parameter.cibir_encoding.offset': 'offset',
 'tls.quic.parameter.enable_time_stamp_v2': 'Enable TimestampV2',
 'tls.quic.parameter.facebook.partial_reliability': 'Facebook Partial Reliability',
 'tls.quic.parameter.google.connection_options': 'Google Connection options',
 'tls.quic.parameter.google.initial_rtt': 'Google Initial RTT',
 'tls.quic.parameter.google.key_update_not_yet_supported': 'Google Key Update not yet supported',
 'tls.quic.parameter.google.quic_params': 'Google QUIC parameters',
 'tls.quic.parameter.google.quic_params_unknown_field': 'Google Unknown Field',
 'tls.quic.parameter.google.quic_version': 'Google QUIC version',
 'tls.quic.parameter.google.support_handshake_done': 'Google Support Handshake Done',
 'tls.quic.parameter.google.supported_version': 'Google Supported Version',
 'tls.quic.parameter.google.supported_versions_length': 'Google Supported Versions Length',
 'tls.quic.parameter.google.user_agent': 'Google UserAgent',
 'tls.quic.parameter.idle_timeout': 'idle_timeout',
 'tls.quic.parameter.initial_max_data': 'initial_max_data',
 'tls.quic.parameter.initial_max_stream_data_bidi_local': 'initial_max_stream_data_bidi_local',
 'tls.quic.parameter.initial_max_stream_data_bidi_remote': 'initial_max_stream_data_bidi_remote',
 'tls.quic.parameter.initial_max_stream_data_uni': 'initial_max_stream_data_uni',
 'tls.quic.parameter.initial_max_streams_bidi': 'initial_max_streams_bidi',
 'tls.quic.parameter.initial_max_streams_uni': 'initial_max_streams_uni',
 'tls.quic.parameter.initial_source_connection_id': 'Initial Source Connection ID',
 'tls.quic.parameter.lengt.old': 'Length',
 'tls.quic.parameter.length': 'Length',
 'tls.quic.parameter.loss_bits': 'loss_bits',
 'tls.quic.parameter.max_ack_delay': 'max_ack_delay',
 'tls.quic.parameter.max_datagram_frame_size': 'max_datagram_frame_size',
 'tls.quic.parameter.max_idle_timeout': 'max_idle_timeout',
 'tls.quic.parameter.max_packet_size': 'max_packet_size',
 'tls.quic.parameter.max_udp_payload_size': 'max_udp_payload_size',
 'tls.quic.parameter.min_ack_delay': 'min_ack_delay',
 'tls.quic.parameter.ocid': 'original_connection_id',
 'tls.quic.parameter.original_destination_connection_id': 'original_destination_connection_id',
 'tls.quic.parameter.preferred_address.connectionid': 'connectionId',
 'tls.quic.parameter.preferred_address.connectionid.length': 'Length',
 'tls.quic.parameter.preferred_address.ipaddress.length': 'Length',
 'tls.quic.parameter.preferred_address.ipv4address': 'ipv4Address',
 'tls.quic.parameter.preferred_address.ipv4port': 'ipv4Port',
 'tls.quic.parameter.preferred_address.ipv6address': 'ipv6Address',
 'tls.quic.parameter.preferred_address.ipv6port': 'ipv6Port',
 'tls.quic.parameter.preferred_address.ipversion': 'ipVersion',
 'tls.quic.parameter.preferred_address.statelessresettoken': 'statelessResetToken',
 'tls.quic.parameter.retry_source_connection_id': 'Retry Source Connection ID',
 'tls.quic.parameter.stateless_reset_token': 'stateless_reset_token',
 'tls.quic.parameter.type': 'Type',
 'tls.quic.parameter.value': 'Value',
 'tls.quic.parameter.vi.chosen_version': 'Chosen Version',
 'tls.quic.parameter.vi.other_version': 'Other Version',
 'tls.quic.parameter.vn.compatible_version': 'Compatible Version',
 'tls.quic.parameter.vn.compatible_version_count': 'Compatible Version Count',
 'tls.quic.parameter.vn.currently_attempted_version': 'Currently Attempted Version',
 'tls.quic.parameter.vn.negotiated_version': 'Negotiated Version',
 'tls.quic.parameter.vn.previously_attempted_version': 'Previously Attempted Version',
 'tls.quic.parameter.vn.received_negotiation_version': 'Received Negotiation Version',
 'tls.quic.parameter.vn.received_negotiation_version_count': 'Received Negotiation Version Count',
 'tls.quic.parameter.vn.supported_version': 'Supported Version',
 'tls.quic.parameter.vn.supported_version_count': 'Supported Version Count',
 'tls.quic.supported_versions': 'Supported Versions',
 'tls.quic.supported_versions.len': 'Supported Versions Length',
 'tls.reassembled.data': 'Reassembled PDU data',
 'tls.reassembled.length': 'Reassembled PDU length',
 'tls.reassembled_in': 'Reassembled PDU in frame',
 'tls.record': 'Record Layer',
 'tls.record.content_type': 'Content Type',
 'tls.record.is_escape': 'Is Escape',
 'tls.record.length': 'Length',
 'tls.record.length.invalid': 'Record fragment length is too small or too large',
 'tls.record.opaque_type': 'Opaque Type',
 'tls.record.padding_length': 'Padding Length',
 'tls.record.version': 'Version',
 'tls.record_size_limit': 'Record Size Limit',
 'tls.resumed': 'This session reuses previously negotiated keys (Session resumption)',
 'tls.sct.sct_extensions': 'Extensions',
 'tls.sct.sct_extensions_length': 'Extensions length',
 'tls.sct.sct_length': 'Serialized SCT Length',
 'tls.sct.sct_logid': 'Log ID',
 'tls.sct.sct_signature': 'Signature',
 'tls.sct.sct_signature_length': 'Signature Length',
 'tls.sct.sct_timestamp': 'Timestamp',
 'tls.sct.sct_version': 'SCT Version',
 'tls.sct.scts_length': 'Serialized SCT List Length',
 'tls.segment': 'TLS segment',
 'tls.segment.count': 'Segment count',
 'tls.segment.data': 'TLS segment data',
 'tls.segment.error': 'Reassembling error',
 'tls.segment.multipletails': 'Multiple tail segments found',
 'tls.segment.overlap': 'Segment overlap',
 'tls.segment.overlap.conflict': 'Conflicting data in segment overlap',
 'tls.segment.toolongfragment': 'Segment too long',
 'tls.segments': 'Reassembled TLS segments',
 'tls.unexpected_message': 'Unexpected message',
 'http.accept': 'Accept',
 'http.accept_encoding': 'Accept Encoding',
 'http.accept_language': 'Accept-Language',
 'http.authbasic': 'Credentials',
 'http.authcitrix': 'Citrix AG Auth',
 'http.authcitrix.domain': 'Citrix AG Domain',
 'http.authcitrix.password': 'Citrix AG Password',
 'http.authcitrix.session': 'Citrix AG Session ID',
 'http.authcitrix.user': 'Citrix AG Username',
 'http.authorization': 'Authorization',
 'http.bad_header_name': 'Illegal characters found in header name',
 'http.cache_control': 'Cache-Control',
 'http.chat': 'Formatted text',
 'http.chunk_boundary': 'Chunk boundary',
 'http.chunk_size': 'Chunk size',
 'http.chunkd_and_length': 'Expert Info',
 'http.chunked_trailer_part': 'trailer-part',
 'http.connection': 'Connection',
 'http.content_encoding': 'Content-Encoding',
 'http.content_length': 'Content length',
 'http.content_length_header': 'Content-Length',
 'http.content_type': 'Content-Type',
 'http.cookie': 'Cookie',
 'http.cookie_pair': 'Cookie pair',
 'http.date': 'Date',
 'http.file_data': 'File Data',
 'http.host': 'Host',
 'http.last_modified': 'Last-Modified',
 'http.leading_crlf': 'Leading CRLF previous message in the stream may have extra CRLF',
 'http.location': 'Location',
 'http.next_request_in': 'Next request in frame',
 'http.next_response_in': 'Next response in frame',
 'http.notification': 'Notification',
 'http.prev_request_in': 'Prev request in frame',
 'http.prev_response_in': 'Prev response in frame',
 'http.proxy_authenticate': 'Proxy-Authenticate',
 'http.proxy_authorization': 'Proxy-Authorization',
 'http.proxy_connect_host': 'Proxy-Connect-Hostname',
 'http.proxy_connect_port': 'Proxy-Connect-Port',
 'http.referer': 'Referer',
 'http.request': 'Request',
 'http.request.full_uri': 'Full request URI',
 'http.request.line': 'Request line',
 'http.request.method': 'Request Method',
 'http.request.uri': 'Request URI',
 'http.request.uri.path': 'Request URI Path',
 'http.request.uri.query': 'Request URI Query',
 'http.request.uri.query.parameter': 'Request URI Query Parameter',
 'http.request.version': 'Request Version',
 'http.request_in': 'Request in frame',
 'http.request_number': 'Request number',
 'http.response': 'Response',
 'http.response.code': 'Status Code',
 'http.response.code.desc': 'Status Code Description',
 'http.response.line': 'Response line',
 'http.response.phrase': 'Response Phrase',
 'http.response.version': 'Response Version',
 'http.response_for.uri': 'Request URI',
 'http.response_in': 'Response in frame',
 'http.response_number': 'Response number',
 'http.sec_websocket_accept': 'Sec-WebSocket-Accept',
 'http.sec_websocket_extensions': 'Sec-WebSocket-Extensions',
 'http.sec_websocket_key': 'Sec-WebSocket-Key',
 'http.sec_websocket_protocol': 'Sec-WebSocket-Protocol',
 'http.sec_websocket_version': 'Sec-WebSocket-Version',
 'http.server': 'Server',
 'http.set_cookie': 'Set-Cookie',
 'http.ssl_port': 'Unencrypted HTTP protocol detected over encrypted port, could indicate a dangerous misconfiguration.',
 'http.subdissector_failed': 'HTTP body subdissector failed, trying heuristic subdissector',
 'http.te_and_length': 'The Content-Length and Transfer-Encoding header must not be set together',
 'http.te_unknown': 'Unknown transfer coding name in Transfer-Encoding header',
 'http.time': 'Time since request',
 'http.tls_port': 'Unencrypted HTTP protocol detected over encrypted port, could indicate a dangerous misconfiguration.',
 'http.transfer_encoding': 'Transfer-Encoding',
 'http.unknown_header': 'Unknown header',
 'http.upgrade': 'Upgrade',
 'http.user_agent': 'User-Agent',
 'http.www_authenticate': 'WWW-Authenticate',
 'http.x_forwarded_for': 'X-Forwarded-For'}